//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: AccidentAnalysisClassificationEventProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
// Note: requires additional types generated from: Enums/AccidentAnalysisClassificationAssistanceTypeProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AccidentAnalysisClassificationEvent")]
  public partial class AccidentAnalysisClassificationEvent : global::ProtoBuf.IExtensible
  {
    public AccidentAnalysisClassificationEvent()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.AccidentAnalysisClassificationEvent,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private float? _CurrentAccelerometerX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"current_accelerometer_x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float CurrentAccelerometerX
    {
      get { return _CurrentAccelerometerX?? default(float); }
      set { _CurrentAccelerometerX = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool CurrentAccelerometerXSpecified
    {
      get { return this._CurrentAccelerometerX != null; }
      set { if (value == (this._CurrentAccelerometerX== null)) this._CurrentAccelerometerX = value ? this.CurrentAccelerometerX : (float?)null; }
    }
    private bool ShouldSerializecurrent_accelerometer_x() { return CurrentAccelerometerXSpecified; }
    private void Resetcurrent_accelerometer_x() { CurrentAccelerometerXSpecified = false; }
    
    private float? _CurrentAccelerometerY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"current_accelerometer_y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float CurrentAccelerometerY
    {
      get { return _CurrentAccelerometerY?? default(float); }
      set { _CurrentAccelerometerY = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool CurrentAccelerometerYSpecified
    {
      get { return this._CurrentAccelerometerY != null; }
      set { if (value == (this._CurrentAccelerometerY== null)) this._CurrentAccelerometerY = value ? this.CurrentAccelerometerY : (float?)null; }
    }
    private bool ShouldSerializecurrent_accelerometer_y() { return CurrentAccelerometerYSpecified; }
    private void Resetcurrent_accelerometer_y() { CurrentAccelerometerYSpecified = false; }
    
    private float? _CurrentAccelerometerZ;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"current_accelerometer_z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float CurrentAccelerometerZ
    {
      get { return _CurrentAccelerometerZ?? default(float); }
      set { _CurrentAccelerometerZ = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool CurrentAccelerometerZSpecified
    {
      get { return this._CurrentAccelerometerZ != null; }
      set { if (value == (this._CurrentAccelerometerZ== null)) this._CurrentAccelerometerZ = value ? this.CurrentAccelerometerZ : (float?)null; }
    }
    private bool ShouldSerializecurrent_accelerometer_z() { return CurrentAccelerometerZSpecified; }
    private void Resetcurrent_accelerometer_z() { CurrentAccelerometerZSpecified = false; }
    
    private uint? _AccidentClassificationNumber;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"accident_classification_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AccidentClassificationNumber
    {
      get { return _AccidentClassificationNumber?? default(uint); }
      set { _AccidentClassificationNumber = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool AccidentClassificationNumberSpecified
    {
      get { return this._AccidentClassificationNumber != null; }
      set { if (value == (this._AccidentClassificationNumber== null)) this._AccidentClassificationNumber = value ? this.AccidentClassificationNumber : (uint?)null; }
    }
    private bool ShouldSerializeaccident_classification_number() { return AccidentClassificationNumberSpecified; }
    private void Resetaccident_classification_number() { AccidentClassificationNumberSpecified = false; }
    
    private uint? _TotalNumberOfImpacts;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"total_number_of_impacts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TotalNumberOfImpacts
    {
      get { return _TotalNumberOfImpacts?? default(uint); }
      set { _TotalNumberOfImpacts = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TotalNumberOfImpactsSpecified
    {
      get { return this._TotalNumberOfImpacts != null; }
      set { if (value == (this._TotalNumberOfImpacts== null)) this._TotalNumberOfImpacts = value ? this.TotalNumberOfImpacts : (uint?)null; }
    }
    private bool ShouldSerializetotal_number_of_impacts() { return TotalNumberOfImpactsSpecified; }
    private void Resettotal_number_of_impacts() { TotalNumberOfImpactsSpecified = false; }
    
    private uint? _NumberOfLowImpacts;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"number_of_low_impacts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint NumberOfLowImpacts
    {
      get { return _NumberOfLowImpacts?? default(uint); }
      set { _NumberOfLowImpacts = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool NumberOfLowImpactsSpecified
    {
      get { return this._NumberOfLowImpacts != null; }
      set { if (value == (this._NumberOfLowImpacts== null)) this._NumberOfLowImpacts = value ? this.NumberOfLowImpacts : (uint?)null; }
    }
    private bool ShouldSerializenumber_of_low_impacts() { return NumberOfLowImpactsSpecified; }
    private void Resetnumber_of_low_impacts() { NumberOfLowImpactsSpecified = false; }
    
    private uint? _NumberOfHighImpacts;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"number_of_high_impacts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint NumberOfHighImpacts
    {
      get { return _NumberOfHighImpacts?? default(uint); }
      set { _NumberOfHighImpacts = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool NumberOfHighImpactsSpecified
    {
      get { return this._NumberOfHighImpacts != null; }
      set { if (value == (this._NumberOfHighImpacts== null)) this._NumberOfHighImpacts = value ? this.NumberOfHighImpacts : (uint?)null; }
    }
    private bool ShouldSerializenumber_of_high_impacts() { return NumberOfHighImpactsSpecified; }
    private void Resetnumber_of_high_impacts() { NumberOfHighImpactsSpecified = false; }
    
    private uint? _NumberOfFrontalImpacts;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"number_of_frontal_impacts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint NumberOfFrontalImpacts
    {
      get { return _NumberOfFrontalImpacts?? default(uint); }
      set { _NumberOfFrontalImpacts = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool NumberOfFrontalImpactsSpecified
    {
      get { return this._NumberOfFrontalImpacts != null; }
      set { if (value == (this._NumberOfFrontalImpacts== null)) this._NumberOfFrontalImpacts = value ? this.NumberOfFrontalImpacts : (uint?)null; }
    }
    private bool ShouldSerializenumber_of_frontal_impacts() { return NumberOfFrontalImpactsSpecified; }
    private void Resetnumber_of_frontal_impacts() { NumberOfFrontalImpactsSpecified = false; }
    
    private uint? _NumberOfRearImpacts;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"number_of_rear_impacts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint NumberOfRearImpacts
    {
      get { return _NumberOfRearImpacts?? default(uint); }
      set { _NumberOfRearImpacts = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool NumberOfRearImpactsSpecified
    {
      get { return this._NumberOfRearImpacts != null; }
      set { if (value == (this._NumberOfRearImpacts== null)) this._NumberOfRearImpacts = value ? this.NumberOfRearImpacts : (uint?)null; }
    }
    private bool ShouldSerializenumber_of_rear_impacts() { return NumberOfRearImpactsSpecified; }
    private void Resetnumber_of_rear_impacts() { NumberOfRearImpactsSpecified = false; }
    
    private uint? _NumberOfSideImpacts;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"number_of_side_impacts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint NumberOfSideImpacts
    {
      get { return _NumberOfSideImpacts?? default(uint); }
      set { _NumberOfSideImpacts = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool NumberOfSideImpactsSpecified
    {
      get { return this._NumberOfSideImpacts != null; }
      set { if (value == (this._NumberOfSideImpacts== null)) this._NumberOfSideImpacts = value ? this.NumberOfSideImpacts : (uint?)null; }
    }
    private bool ShouldSerializenumber_of_side_impacts() { return NumberOfSideImpactsSpecified; }
    private void Resetnumber_of_side_impacts() { NumberOfSideImpactsSpecified = false; }
    
    private uint? _NumberOfCornerImpacts;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"number_of_corner_impacts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint NumberOfCornerImpacts
    {
      get { return _NumberOfCornerImpacts?? default(uint); }
      set { _NumberOfCornerImpacts = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool NumberOfCornerImpactsSpecified
    {
      get { return this._NumberOfCornerImpacts != null; }
      set { if (value == (this._NumberOfCornerImpacts== null)) this._NumberOfCornerImpacts = value ? this.NumberOfCornerImpacts : (uint?)null; }
    }
    private bool ShouldSerializenumber_of_corner_impacts() { return NumberOfCornerImpactsSpecified; }
    private void Resetnumber_of_corner_impacts() { NumberOfCornerImpactsSpecified = false; }
    
    private uint? _StationaryTimeSeconds;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"stationary_time_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint StationaryTimeSeconds
    {
      get { return _StationaryTimeSeconds?? default(uint); }
      set { _StationaryTimeSeconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool StationaryTimeSecondsSpecified
    {
      get { return this._StationaryTimeSeconds != null; }
      set { if (value == (this._StationaryTimeSeconds== null)) this._StationaryTimeSeconds = value ? this.StationaryTimeSeconds : (uint?)null; }
    }
    private bool ShouldSerializestationary_time_seconds() { return StationaryTimeSecondsSpecified; }
    private void Resetstationary_time_seconds() { StationaryTimeSecondsSpecified = false; }
    
    private AccidentAnalysisClassificationAssistanceType? _AssistanceType;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"AssistanceType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public AccidentAnalysisClassificationAssistanceType AssistanceType
    {
      get { return _AssistanceType?? AccidentAnalysisClassificationAssistanceType.ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_NOTHING; }
      set { _AssistanceType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool AssistanceTypeSpecified
    {
      get { return this._AssistanceType != null; }
      set { if (value == (this._AssistanceType== null)) this._AssistanceType = value ? this.AssistanceType : (AccidentAnalysisClassificationAssistanceType?)null; }
    }
    private bool ShouldSerializeAssistanceType() { return AssistanceTypeSpecified; }
    private void ResetAssistanceType() { AssistanceTypeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}