//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Analog1LowProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Analog1Low")]
  public partial class Analog1Low : global::ProtoBuf.IExtensible
  {
    public Analog1Low()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.Analog1Low,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _DurationSeconds;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"duration_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint DurationSeconds
    {
      get { return _DurationSeconds?? default(uint); }
      set { _DurationSeconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DurationSecondsSpecified
    {
      get { return this._DurationSeconds != null; }
      set { if (value == (this._DurationSeconds== null)) this._DurationSeconds = value ? this.DurationSeconds : (uint?)null; }
    }
    private bool ShouldSerializeduration_seconds() { return DurationSecondsSpecified; }
    private void Resetduration_seconds() { DurationSecondsSpecified = false; }
    
    private uint? _ThresholdVolts;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"threshold_volts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ThresholdVolts
    {
      get { return _ThresholdVolts?? default(uint); }
      set { _ThresholdVolts = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ThresholdVoltsSpecified
    {
      get { return this._ThresholdVolts != null; }
      set { if (value == (this._ThresholdVolts== null)) this._ThresholdVolts = value ? this.ThresholdVolts : (uint?)null; }
    }
    private bool ShouldSerializethreshold_volts() { return ThresholdVoltsSpecified; }
    private void Resetthreshold_volts() { ThresholdVoltsSpecified = false; }
    
    private uint? _ValueVolts;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"value_volts", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ValueVolts
    {
      get { return _ValueVolts?? default(uint); }
      set { _ValueVolts = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ValueVoltsSpecified
    {
      get { return this._ValueVolts != null; }
      set { if (value == (this._ValueVolts== null)) this._ValueVolts = value ? this.ValueVolts : (uint?)null; }
    }
    private bool ShouldSerializevalue_volts() { return ValueVoltsSpecified; }
    private void Resetvalue_volts() { ValueVoltsSpecified = false; }
    
    private uint? _DelaySeconds;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"delay_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint DelaySeconds
    {
      get { return _DelaySeconds?? default(uint); }
      set { _DelaySeconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DelaySecondsSpecified
    {
      get { return this._DelaySeconds != null; }
      set { if (value == (this._DelaySeconds== null)) this._DelaySeconds = value ? this.DelaySeconds : (uint?)null; }
    }
    private bool ShouldSerializedelay_seconds() { return DelaySecondsSpecified; }
    private void Resetdelay_seconds() { DelaySecondsSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}