//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: BatteryCrankProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BatteryCrank")]
  public partial class BatteryCrank : global::ProtoBuf.IExtensible
  {
    public BatteryCrank()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.BatteryCrank,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private float? _VoltageAverageBeforeCrank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"voltage_average_before_crank", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float VoltageAverageBeforeCrank
    {
      get { return _VoltageAverageBeforeCrank?? default(float); }
      set { _VoltageAverageBeforeCrank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool VoltageAverageBeforeCrankSpecified
    {
      get { return this._VoltageAverageBeforeCrank != null; }
      set { if (value == (this._VoltageAverageBeforeCrank== null)) this._VoltageAverageBeforeCrank = value ? this.VoltageAverageBeforeCrank : (float?)null; }
    }
    private bool ShouldSerializevoltage_average_before_crank() { return VoltageAverageBeforeCrankSpecified; }
    private void Resetvoltage_average_before_crank() { VoltageAverageBeforeCrankSpecified = false; }
    
    private float? _VoltageMinimum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"voltage_minimum", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float VoltageMinimum
    {
      get { return _VoltageMinimum?? default(float); }
      set { _VoltageMinimum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool VoltageMinimumSpecified
    {
      get { return this._VoltageMinimum != null; }
      set { if (value == (this._VoltageMinimum== null)) this._VoltageMinimum = value ? this.VoltageMinimum : (float?)null; }
    }
    private bool ShouldSerializevoltage_minimum() { return VoltageMinimumSpecified; }
    private void Resetvoltage_minimum() { VoltageMinimumSpecified = false; }
    
    private uint? _VoltageMinimumDurationMilliseconds;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"voltage_minimum_duration_milliseconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint VoltageMinimumDurationMilliseconds
    {
      get { return _VoltageMinimumDurationMilliseconds?? default(uint); }
      set { _VoltageMinimumDurationMilliseconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool VoltageMinimumDurationMillisecondsSpecified
    {
      get { return this._VoltageMinimumDurationMilliseconds != null; }
      set { if (value == (this._VoltageMinimumDurationMilliseconds== null)) this._VoltageMinimumDurationMilliseconds = value ? this.VoltageMinimumDurationMilliseconds : (uint?)null; }
    }
    private bool ShouldSerializevoltage_minimum_duration_milliseconds() { return VoltageMinimumDurationMillisecondsSpecified; }
    private void Resetvoltage_minimum_duration_milliseconds() { VoltageMinimumDurationMillisecondsSpecified = false; }
    
    private float? _VoltageCrankAverage;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"voltage_crank_average", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float VoltageCrankAverage
    {
      get { return _VoltageCrankAverage?? default(float); }
      set { _VoltageCrankAverage = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool VoltageCrankAverageSpecified
    {
      get { return this._VoltageCrankAverage != null; }
      set { if (value == (this._VoltageCrankAverage== null)) this._VoltageCrankAverage = value ? this.VoltageCrankAverage : (float?)null; }
    }
    private bool ShouldSerializevoltage_crank_average() { return VoltageCrankAverageSpecified; }
    private void Resetvoltage_crank_average() { VoltageCrankAverageSpecified = false; }
    
    private uint? _VoltageCrankAverageDurationMilliseconds;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"voltage_crank_average_duration_milliseconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint VoltageCrankAverageDurationMilliseconds
    {
      get { return _VoltageCrankAverageDurationMilliseconds?? default(uint); }
      set { _VoltageCrankAverageDurationMilliseconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool VoltageCrankAverageDurationMillisecondsSpecified
    {
      get { return this._VoltageCrankAverageDurationMilliseconds != null; }
      set { if (value == (this._VoltageCrankAverageDurationMilliseconds== null)) this._VoltageCrankAverageDurationMilliseconds = value ? this.VoltageCrankAverageDurationMilliseconds : (uint?)null; }
    }
    private bool ShouldSerializevoltage_crank_average_duration_milliseconds() { return VoltageCrankAverageDurationMillisecondsSpecified; }
    private void Resetvoltage_crank_average_duration_milliseconds() { VoltageCrankAverageDurationMillisecondsSpecified = false; }
    
    private float? _VoltagePostCrank;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"voltage_post_crank", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float VoltagePostCrank
    {
      get { return _VoltagePostCrank?? default(float); }
      set { _VoltagePostCrank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool VoltagePostCrankSpecified
    {
      get { return this._VoltagePostCrank != null; }
      set { if (value == (this._VoltagePostCrank== null)) this._VoltagePostCrank = value ? this.VoltagePostCrank : (float?)null; }
    }
    private bool ShouldSerializevoltage_post_crank() { return VoltagePostCrankSpecified; }
    private void Resetvoltage_post_crank() { VoltagePostCrankSpecified = false; }
    
    private int? _Temperature;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"temperature", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Temperature
    {
      get { return _Temperature?? default(int); }
      set { _Temperature = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TemperatureSpecified
    {
      get { return this._Temperature != null; }
      set { if (value == (this._Temperature== null)) this._Temperature = value ? this.Temperature : (int?)null; }
    }
    private bool ShouldSerializetemperature() { return TemperatureSpecified; }
    private void Resettemperature() { TemperatureSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}