//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: BatteryLowProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BatteryLow")]
  public partial class BatteryLow : global::ProtoBuf.IExtensible
  {
    public BatteryLow()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.BatteryLow,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private int? _Temperature;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"temperature", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Temperature
    {
      get { return _Temperature?? default(int); }
      set { _Temperature = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TemperatureSpecified
    {
      get { return this._Temperature != null; }
      set { if (value == (this._Temperature== null)) this._Temperature = value ? this.Temperature : (int?)null; }
    }
    private bool ShouldSerializetemperature() { return TemperatureSpecified; }
    private void Resettemperature() { TemperatureSpecified = false; }
    
    private uint? _Voltage;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"voltage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Voltage
    {
      get { return _Voltage?? default(uint); }
      set { _Voltage = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool VoltageSpecified
    {
      get { return this._Voltage != null; }
      set { if (value == (this._Voltage== null)) this._Voltage = value ? this.Voltage : (uint?)null; }
    }
    private bool ShouldSerializevoltage() { return VoltageSpecified; }
    private void Resetvoltage() { VoltageSpecified = false; }
    
    private uint? _BatteryAge;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"battery_age", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BatteryAge
    {
      get { return _BatteryAge?? default(uint); }
      set { _BatteryAge = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool BatteryAgeSpecified
    {
      get { return this._BatteryAge != null; }
      set { if (value == (this._BatteryAge== null)) this._BatteryAge = value ? this.BatteryAge : (uint?)null; }
    }
    private bool ShouldSerializebattery_age() { return BatteryAgeSpecified; }
    private void Resetbattery_age() { BatteryAgeSpecified = false; }
    
    private uint? _ChargeLevelPercentage;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"charge_level_percentage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ChargeLevelPercentage
    {
      get { return _ChargeLevelPercentage?? default(uint); }
      set { _ChargeLevelPercentage = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ChargeLevelPercentageSpecified
    {
      get { return this._ChargeLevelPercentage != null; }
      set { if (value == (this._ChargeLevelPercentage== null)) this._ChargeLevelPercentage = value ? this.ChargeLevelPercentage : (uint?)null; }
    }
    private bool ShouldSerializecharge_level_percentage() { return ChargeLevelPercentageSpecified; }
    private void Resetcharge_level_percentage() { ChargeLevelPercentageSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}