//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: BluetoothLowEnergyIOProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
// Note: requires additional types generated from: Enums/BluetoothLowEnergyIOReasonTypeProto.proto
// Note: requires additional types generated from: Enums/BluetoothLowEnergyDeviceClassTypeProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BluetoothLowEnergyIO")]
  public partial class BluetoothLowEnergyIO : global::ProtoBuf.IExtensible
  {
    public BluetoothLowEnergyIO()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.BluetoothLowEnergyIO,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private BluetoothLowEnergyIOReasonType? _Reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BluetoothLowEnergyIOReasonType Reason
    {
      get { return _Reason?? BluetoothLowEnergyIOReasonType.BLUETOOTH_LOW_ENERGY_IO_REASON_UNDEFINED; }
      set { _Reason = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ReasonSpecified
    {
      get { return this._Reason != null; }
      set { if (value == (this._Reason== null)) this._Reason = value ? this.Reason : (BluetoothLowEnergyIOReasonType?)null; }
    }
    private bool ShouldSerializereason() { return ReasonSpecified; }
    private void Resetreason() { ReasonSpecified = false; }
    
    private ulong? _DeviceId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"device_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong DeviceId
    {
      get { return _DeviceId?? default(ulong); }
      set { _DeviceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DeviceIdSpecified
    {
      get { return this._DeviceId != null; }
      set { if (value == (this._DeviceId== null)) this._DeviceId = value ? this.DeviceId : (ulong?)null; }
    }
    private bool ShouldSerializedevice_id() { return DeviceIdSpecified; }
    private void Resetdevice_id() { DeviceIdSpecified = false; }
    
    private BluetoothLowEnergyDeviceClassType? _DeviceClass;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"device_class", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public BluetoothLowEnergyDeviceClassType DeviceClass
    {
      get { return _DeviceClass?? BluetoothLowEnergyDeviceClassType.BLUETOOTH_LOW_ENERGY_DEVICE_CLASS_UNDEFINED; }
      set { _DeviceClass = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DeviceClassSpecified
    {
      get { return this._DeviceClass != null; }
      set { if (value == (this._DeviceClass== null)) this._DeviceClass = value ? this.DeviceClass : (BluetoothLowEnergyDeviceClassType?)null; }
    }
    private bool ShouldSerializedevice_class() { return DeviceClassSpecified; }
    private void Resetdevice_class() { DeviceClassSpecified = false; }
    
    private uint? _ReceivedSignalStrength;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"received_signal_strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ReceivedSignalStrength
    {
      get { return _ReceivedSignalStrength?? default(uint); }
      set { _ReceivedSignalStrength = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ReceivedSignalStrengthSpecified
    {
      get { return this._ReceivedSignalStrength != null; }
      set { if (value == (this._ReceivedSignalStrength== null)) this._ReceivedSignalStrength = value ? this.ReceivedSignalStrength : (uint?)null; }
    }
    private bool ShouldSerializereceived_signal_strength() { return ReceivedSignalStrengthSpecified; }
    private void Resetreceived_signal_strength() { ReceivedSignalStrengthSpecified = false; }
    
    private uint? _AdvertisingIntervalSeconds;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"advertising_interval_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AdvertisingIntervalSeconds
    {
      get { return _AdvertisingIntervalSeconds?? default(uint); }
      set { _AdvertisingIntervalSeconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool AdvertisingIntervalSecondsSpecified
    {
      get { return this._AdvertisingIntervalSeconds != null; }
      set { if (value == (this._AdvertisingIntervalSeconds== null)) this._AdvertisingIntervalSeconds = value ? this.AdvertisingIntervalSeconds : (uint?)null; }
    }
    private bool ShouldSerializeadvertising_interval_seconds() { return AdvertisingIntervalSecondsSpecified; }
    private void Resetadvertising_interval_seconds() { AdvertisingIntervalSecondsSpecified = false; }
    
    private uint? _BatteryLevelPercentage;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"battery_level_percentage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BatteryLevelPercentage
    {
      get { return _BatteryLevelPercentage?? default(uint); }
      set { _BatteryLevelPercentage = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool BatteryLevelPercentageSpecified
    {
      get { return this._BatteryLevelPercentage != null; }
      set { if (value == (this._BatteryLevelPercentage== null)) this._BatteryLevelPercentage = value ? this.BatteryLevelPercentage : (uint?)null; }
    }
    private bool ShouldSerializebattery_level_percentage() { return BatteryLevelPercentageSpecified; }
    private void Resetbattery_level_percentage() { BatteryLevelPercentageSpecified = false; }
    
    private ulong? _AccelerometerRawValues;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"accelerometer_raw_values", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong AccelerometerRawValues
    {
      get { return _AccelerometerRawValues?? default(ulong); }
      set { _AccelerometerRawValues = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool AccelerometerRawValuesSpecified
    {
      get { return this._AccelerometerRawValues != null; }
      set { if (value == (this._AccelerometerRawValues== null)) this._AccelerometerRawValues = value ? this.AccelerometerRawValues : (ulong?)null; }
    }
    private bool ShouldSerializeaccelerometer_raw_values() { return AccelerometerRawValuesSpecified; }
    private void Resetaccelerometer_raw_values() { AccelerometerRawValuesSpecified = false; }
    
    private uint? _LedsOnState;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"leds_on_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LedsOnState
    {
      get { return _LedsOnState?? default(uint); }
      set { _LedsOnState = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool LedsOnStateSpecified
    {
      get { return this._LedsOnState != null; }
      set { if (value == (this._LedsOnState== null)) this._LedsOnState = value ? this.LedsOnState : (uint?)null; }
    }
    private bool ShouldSerializeleds_on_state() { return LedsOnStateSpecified; }
    private void Resetleds_on_state() { LedsOnStateSpecified = false; }
    
    private uint? _LedsFlashingState;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"leds_flashing_state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LedsFlashingState
    {
      get { return _LedsFlashingState?? default(uint); }
      set { _LedsFlashingState = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool LedsFlashingStateSpecified
    {
      get { return this._LedsFlashingState != null; }
      set { if (value == (this._LedsFlashingState== null)) this._LedsFlashingState = value ? this.LedsFlashingState : (uint?)null; }
    }
    private bool ShouldSerializeleds_flashing_state() { return LedsFlashingStateSpecified; }
    private void Resetleds_flashing_state() { LedsFlashingStateSpecified = false; }
    
    private uint? _Inputs;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"inputs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Inputs
    {
      get { return _Inputs?? default(uint); }
      set { _Inputs = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool InputsSpecified
    {
      get { return this._Inputs != null; }
      set { if (value == (this._Inputs== null)) this._Inputs = value ? this.Inputs : (uint?)null; }
    }
    private bool ShouldSerializeinputs() { return InputsSpecified; }
    private void Resetinputs() { InputsSpecified = false; }
    
    private uint? _Outputs;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"outputs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Outputs
    {
      get { return _Outputs?? default(uint); }
      set { _Outputs = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool OutputsSpecified
    {
      get { return this._Outputs != null; }
      set { if (value == (this._Outputs== null)) this._Outputs = value ? this.Outputs : (uint?)null; }
    }
    private bool ShouldSerializeoutputs() { return OutputsSpecified; }
    private void Resetoutputs() { OutputsSpecified = false; }
    
    private float? _TemperatureDegrees;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"temperature_degrees", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float TemperatureDegrees
    {
      get { return _TemperatureDegrees?? default(float); }
      set { _TemperatureDegrees = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TemperatureDegreesSpecified
    {
      get { return this._TemperatureDegrees != null; }
      set { if (value == (this._TemperatureDegrees== null)) this._TemperatureDegrees = value ? this.TemperatureDegrees : (float?)null; }
    }
    private bool ShouldSerializetemperature_degrees() { return TemperatureDegreesSpecified; }
    private void Resettemperature_degrees() { TemperatureDegreesSpecified = false; }
    
    private uint? _FirmwareMajorVersion;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"firmware_major_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FirmwareMajorVersion
    {
      get { return _FirmwareMajorVersion?? default(uint); }
      set { _FirmwareMajorVersion = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool FirmwareMajorVersionSpecified
    {
      get { return this._FirmwareMajorVersion != null; }
      set { if (value == (this._FirmwareMajorVersion== null)) this._FirmwareMajorVersion = value ? this.FirmwareMajorVersion : (uint?)null; }
    }
    private bool ShouldSerializefirmware_major_version() { return FirmwareMajorVersionSpecified; }
    private void Resetfirmware_major_version() { FirmwareMajorVersionSpecified = false; }
    
    private uint? _FirmwareMinorVersion;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"firmware_minor_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FirmwareMinorVersion
    {
      get { return _FirmwareMinorVersion?? default(uint); }
      set { _FirmwareMinorVersion = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool FirmwareMinorVersionSpecified
    {
      get { return this._FirmwareMinorVersion != null; }
      set { if (value == (this._FirmwareMinorVersion== null)) this._FirmwareMinorVersion = value ? this.FirmwareMinorVersion : (uint?)null; }
    }
    private bool ShouldSerializefirmware_minor_version() { return FirmwareMinorVersionSpecified; }
    private void Resetfirmware_minor_version() { FirmwareMinorVersionSpecified = false; }
    
    private uint? _ExtenderInputs;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"extender_Inputs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ExtenderInputs
    {
      get { return _ExtenderInputs?? default(uint); }
      set { _ExtenderInputs = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ExtenderInputsSpecified
    {
      get { return this._ExtenderInputs != null; }
      set { if (value == (this._ExtenderInputs== null)) this._ExtenderInputs = value ? this.ExtenderInputs : (uint?)null; }
    }
    private bool ShouldSerializeextender_Inputs() { return ExtenderInputsSpecified; }
    private void Resetextender_Inputs() { ExtenderInputsSpecified = false; }
    
    private uint? _ExtenderOutputs;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"extender_Outputs", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ExtenderOutputs
    {
      get { return _ExtenderOutputs?? default(uint); }
      set { _ExtenderOutputs = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ExtenderOutputsSpecified
    {
      get { return this._ExtenderOutputs != null; }
      set { if (value == (this._ExtenderOutputs== null)) this._ExtenderOutputs = value ? this.ExtenderOutputs : (uint?)null; }
    }
    private bool ShouldSerializeextender_Outputs() { return ExtenderOutputsSpecified; }
    private void Resetextender_Outputs() { ExtenderOutputsSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}