//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: CanVehicleInfoProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CanVehicleInfo")]
  public partial class CanVehicleInfo : global::ProtoBuf.IExtensible
  {
    public CanVehicleInfo()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.CanVehicleInfo,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _InstantaneousFuelEconomy;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"instantaneous_fuel_economy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint InstantaneousFuelEconomy
    {
      get { return _InstantaneousFuelEconomy?? default(uint); }
      set { _InstantaneousFuelEconomy = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool InstantaneousFuelEconomySpecified
    {
      get { return this._InstantaneousFuelEconomy != null; }
      set { if (value == (this._InstantaneousFuelEconomy== null)) this._InstantaneousFuelEconomy = value ? this.InstantaneousFuelEconomy : (uint?)null; }
    }
    private bool ShouldSerializeinstantaneous_fuel_economy() { return InstantaneousFuelEconomySpecified; }
    private void Resetinstantaneous_fuel_economy() { InstantaneousFuelEconomySpecified = false; }
    
    private uint? _BrakeCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"brake_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BrakeCount
    {
      get { return _BrakeCount?? default(uint); }
      set { _BrakeCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool BrakeCountSpecified
    {
      get { return this._BrakeCount != null; }
      set { if (value == (this._BrakeCount== null)) this._BrakeCount = value ? this.BrakeCount : (uint?)null; }
    }
    private bool ShouldSerializebrake_count() { return BrakeCountSpecified; }
    private void Resetbrake_count() { BrakeCountSpecified = false; }
    
    private float? _BrakeDurationSeconds;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"brake_duration_seconds", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float BrakeDurationSeconds
    {
      get { return _BrakeDurationSeconds?? default(float); }
      set { _BrakeDurationSeconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool BrakeDurationSecondsSpecified
    {
      get { return this._BrakeDurationSeconds != null; }
      set { if (value == (this._BrakeDurationSeconds== null)) this._BrakeDurationSeconds = value ? this.BrakeDurationSeconds : (float?)null; }
    }
    private bool ShouldSerializebrake_duration_seconds() { return BrakeDurationSecondsSpecified; }
    private void Resetbrake_duration_seconds() { BrakeDurationSecondsSpecified = false; }
    
    private uint? _EngineLoadPercent;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"engine_load_percent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint EngineLoadPercent
    {
      get { return _EngineLoadPercent?? default(uint); }
      set { _EngineLoadPercent = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool EngineLoadPercentSpecified
    {
      get { return this._EngineLoadPercent != null; }
      set { if (value == (this._EngineLoadPercent== null)) this._EngineLoadPercent = value ? this.EngineLoadPercent : (uint?)null; }
    }
    private bool ShouldSerializeengine_load_percent() { return EngineLoadPercentSpecified; }
    private void Resetengine_load_percent() { EngineLoadPercentSpecified = false; }
    
    private int? _EngineCoolantTemperature;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"engine_coolant_temperature", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int EngineCoolantTemperature
    {
      get { return _EngineCoolantTemperature?? default(int); }
      set { _EngineCoolantTemperature = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool EngineCoolantTemperatureSpecified
    {
      get { return this._EngineCoolantTemperature != null; }
      set { if (value == (this._EngineCoolantTemperature== null)) this._EngineCoolantTemperature = value ? this.EngineCoolantTemperature : (int?)null; }
    }
    private bool ShouldSerializeengine_coolant_temperature() { return EngineCoolantTemperatureSpecified; }
    private void Resetengine_coolant_temperature() { EngineCoolantTemperatureSpecified = false; }
    
    private int? _EngineOilTemperature;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"engine_oil_temperature", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int EngineOilTemperature
    {
      get { return _EngineOilTemperature?? default(int); }
      set { _EngineOilTemperature = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool EngineOilTemperatureSpecified
    {
      get { return this._EngineOilTemperature != null; }
      set { if (value == (this._EngineOilTemperature== null)) this._EngineOilTemperature = value ? this.EngineOilTemperature : (int?)null; }
    }
    private bool ShouldSerializeengine_oil_temperature() { return EngineOilTemperatureSpecified; }
    private void Resetengine_oil_temperature() { EngineOilTemperatureSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}