//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: DailyTripSummaryProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DailyTripSummary")]
  public partial class DailyTripSummary : global::ProtoBuf.IExtensible
  {
    public DailyTripSummary()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.DailyTripSummary,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _TotalTripDistance;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"total_trip_distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TotalTripDistance
    {
      get { return _TotalTripDistance?? default(uint); }
      set { _TotalTripDistance = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TotalTripDistanceSpecified
    {
      get { return this._TotalTripDistance != null; }
      set { if (value == (this._TotalTripDistance== null)) this._TotalTripDistance = value ? this.TotalTripDistance : (uint?)null; }
    }
    private bool ShouldSerializetotal_trip_distance() { return TotalTripDistanceSpecified; }
    private void Resettotal_trip_distance() { TotalTripDistanceSpecified = false; }
    
    private uint? _NumberOfTrips;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"number_of_trips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint NumberOfTrips
    {
      get { return _NumberOfTrips?? default(uint); }
      set { _NumberOfTrips = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool NumberOfTripsSpecified
    {
      get { return this._NumberOfTrips != null; }
      set { if (value == (this._NumberOfTrips== null)) this._NumberOfTrips = value ? this.NumberOfTrips : (uint?)null; }
    }
    private bool ShouldSerializenumber_of_trips() { return NumberOfTripsSpecified; }
    private void Resetnumber_of_trips() { NumberOfTripsSpecified = false; }
    
    private uint? _TotalTripTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"total_trip_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TotalTripTime
    {
      get { return _TotalTripTime?? default(uint); }
      set { _TotalTripTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TotalTripTimeSpecified
    {
      get { return this._TotalTripTime != null; }
      set { if (value == (this._TotalTripTime== null)) this._TotalTripTime = value ? this.TotalTripTime : (uint?)null; }
    }
    private bool ShouldSerializetotal_trip_time() { return TotalTripTimeSpecified; }
    private void Resettotal_trip_time() { TotalTripTimeSpecified = false; }
    
    private uint? _TimeTimeslot1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"time_timeslot1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TimeTimeslot1
    {
      get { return _TimeTimeslot1?? default(uint); }
      set { _TimeTimeslot1 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TimeTimeslot1Specified
    {
      get { return this._TimeTimeslot1 != null; }
      set { if (value == (this._TimeTimeslot1== null)) this._TimeTimeslot1 = value ? this.TimeTimeslot1 : (uint?)null; }
    }
    private bool ShouldSerializetime_timeslot1() { return TimeTimeslot1Specified; }
    private void Resettime_timeslot1() { TimeTimeslot1Specified = false; }
    
    private uint? _TimeTimeslot2;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"time_timeslot2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TimeTimeslot2
    {
      get { return _TimeTimeslot2?? default(uint); }
      set { _TimeTimeslot2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TimeTimeslot2Specified
    {
      get { return this._TimeTimeslot2 != null; }
      set { if (value == (this._TimeTimeslot2== null)) this._TimeTimeslot2 = value ? this.TimeTimeslot2 : (uint?)null; }
    }
    private bool ShouldSerializetime_timeslot2() { return TimeTimeslot2Specified; }
    private void Resettime_timeslot2() { TimeTimeslot2Specified = false; }
    
    private uint? _MaximumSpeed;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"maximum_speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MaximumSpeed
    {
      get { return _MaximumSpeed?? default(uint); }
      set { _MaximumSpeed = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MaximumSpeedSpecified
    {
      get { return this._MaximumSpeed != null; }
      set { if (value == (this._MaximumSpeed== null)) this._MaximumSpeed = value ? this.MaximumSpeed : (uint?)null; }
    }
    private bool ShouldSerializemaximum_speed() { return MaximumSpeedSpecified; }
    private void Resetmaximum_speed() { MaximumSpeedSpecified = false; }
    
    private uint? _TotalSpeedingTime;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"total_speeding_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TotalSpeedingTime
    {
      get { return _TotalSpeedingTime?? default(uint); }
      set { _TotalSpeedingTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TotalSpeedingTimeSpecified
    {
      get { return this._TotalSpeedingTime != null; }
      set { if (value == (this._TotalSpeedingTime== null)) this._TotalSpeedingTime = value ? this.TotalSpeedingTime : (uint?)null; }
    }
    private bool ShouldSerializetotal_speeding_time() { return TotalSpeedingTimeSpecified; }
    private void Resettotal_speeding_time() { TotalSpeedingTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}