//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: DailyGeofenceSummaryProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DailyGeofenceSummary")]
  public partial class DailyGeofenceSummary : global::ProtoBuf.IExtensible
  {
    public DailyGeofenceSummary()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.DailyGeofenceSummary,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _GeofenceType1Entries;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"geofence_type1_entries", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint GeofenceType1Entries
    {
      get { return _GeofenceType1Entries?? default(uint); }
      set { _GeofenceType1Entries = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool GeofenceType1EntriesSpecified
    {
      get { return this._GeofenceType1Entries != null; }
      set { if (value == (this._GeofenceType1Entries== null)) this._GeofenceType1Entries = value ? this.GeofenceType1Entries : (uint?)null; }
    }
    private bool ShouldSerializegeofence_type1_entries() { return GeofenceType1EntriesSpecified; }
    private void Resetgeofence_type1_entries() { GeofenceType1EntriesSpecified = false; }
    
    private uint? _GeofenceType1Time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"geofence_type1_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint GeofenceType1Time
    {
      get { return _GeofenceType1Time?? default(uint); }
      set { _GeofenceType1Time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool GeofenceType1TimeSpecified
    {
      get { return this._GeofenceType1Time != null; }
      set { if (value == (this._GeofenceType1Time== null)) this._GeofenceType1Time = value ? this.GeofenceType1Time : (uint?)null; }
    }
    private bool ShouldSerializegeofence_type1_time() { return GeofenceType1TimeSpecified; }
    private void Resetgeofence_type1_time() { GeofenceType1TimeSpecified = false; }
    
    private uint? _GeofenceType1Distance;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"geofence_type1_distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint GeofenceType1Distance
    {
      get { return _GeofenceType1Distance?? default(uint); }
      set { _GeofenceType1Distance = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool GeofenceType1DistanceSpecified
    {
      get { return this._GeofenceType1Distance != null; }
      set { if (value == (this._GeofenceType1Distance== null)) this._GeofenceType1Distance = value ? this.GeofenceType1Distance : (uint?)null; }
    }
    private bool ShouldSerializegeofence_type1_distance() { return GeofenceType1DistanceSpecified; }
    private void Resetgeofence_type1_distance() { GeofenceType1DistanceSpecified = false; }
    
    private uint? _GeofenceType2Entries;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"geofence_type2_entries", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint GeofenceType2Entries
    {
      get { return _GeofenceType2Entries?? default(uint); }
      set { _GeofenceType2Entries = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool GeofenceType2EntriesSpecified
    {
      get { return this._GeofenceType2Entries != null; }
      set { if (value == (this._GeofenceType2Entries== null)) this._GeofenceType2Entries = value ? this.GeofenceType2Entries : (uint?)null; }
    }
    private bool ShouldSerializegeofence_type2_entries() { return GeofenceType2EntriesSpecified; }
    private void Resetgeofence_type2_entries() { GeofenceType2EntriesSpecified = false; }
    
    private uint? _GeofenceType2Time;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"geofence_type2_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint GeofenceType2Time
    {
      get { return _GeofenceType2Time?? default(uint); }
      set { _GeofenceType2Time = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool GeofenceType2TimeSpecified
    {
      get { return this._GeofenceType2Time != null; }
      set { if (value == (this._GeofenceType2Time== null)) this._GeofenceType2Time = value ? this.GeofenceType2Time : (uint?)null; }
    }
    private bool ShouldSerializegeofence_type2_time() { return GeofenceType2TimeSpecified; }
    private void Resetgeofence_type2_time() { GeofenceType2TimeSpecified = false; }
    
    private uint? _GeofenceType2Distance;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"geofence_type2_distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint GeofenceType2Distance
    {
      get { return _GeofenceType2Distance?? default(uint); }
      set { _GeofenceType2Distance = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool GeofenceType2DistanceSpecified
    {
      get { return this._GeofenceType2Distance != null; }
      set { if (value == (this._GeofenceType2Distance== null)) this._GeofenceType2Distance = value ? this.GeofenceType2Distance : (uint?)null; }
    }
    private bool ShouldSerializegeofence_type2_distance() { return GeofenceType2DistanceSpecified; }
    private void Resetgeofence_type2_distance() { GeofenceType2DistanceSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}