//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: DeviceRemovalProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeviceRemoval")]
  public partial class DeviceRemoval : global::ProtoBuf.IExtensible
  {
    public DeviceRemoval()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.DeviceRemoval,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private string _Vin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"vin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Vin
    {
      get { return _Vin?? ""; }
      set { _Vin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool VinSpecified
    {
      get { return this._Vin != null; }
      set { if (value == (this._Vin== null)) this._Vin = value ? this.Vin : (string)null; }
    }
    private bool ShouldSerializevin() { return VinSpecified; }
    private void Resetvin() { VinSpecified = false; }
    
    private uint? _DisconnectedTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"disconnected_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint DisconnectedTime
    {
      get { return _DisconnectedTime?? default(uint); }
      set { _DisconnectedTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DisconnectedTimeSpecified
    {
      get { return this._DisconnectedTime != null; }
      set { if (value == (this._DisconnectedTime== null)) this._DisconnectedTime = value ? this.DisconnectedTime : (uint?)null; }
    }
    private bool ShouldSerializedisconnected_time() { return DisconnectedTimeSpecified; }
    private void Resetdisconnected_time() { DisconnectedTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}