//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: DevicePlugInProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
// Note: requires additional types generated from: Enums/OBD2ProtocolProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DevicePlugIn")]
  public partial class DevicePlugIn : global::ProtoBuf.IExtensible
  {
    public DevicePlugIn()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.DevicePlugIn,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private string _Vin;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"vin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Vin
    {
      get { return _Vin?? ""; }
      set { _Vin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool VinSpecified
    {
      get { return this._Vin != null; }
      set { if (value == (this._Vin== null)) this._Vin = value ? this.Vin : (string)null; }
    }
    private bool ShouldSerializevin() { return VinSpecified; }
    private void Resetvin() { VinSpecified = false; }
    
    private OBD2Protocol? _Obd2Protocol;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"obd2_protocol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public OBD2Protocol Obd2Protocol
    {
      get { return _Obd2Protocol?? OBD2Protocol.OBD2_PROTOCOL_NOT_SUPPORTED; }
      set { _Obd2Protocol = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Obd2ProtocolSpecified
    {
      get { return this._Obd2Protocol != null; }
      set { if (value == (this._Obd2Protocol== null)) this._Obd2Protocol = value ? this.Obd2Protocol : (OBD2Protocol?)null; }
    }
    private bool ShouldSerializeobd2_protocol() { return Obd2ProtocolSpecified; }
    private void Resetobd2_protocol() { Obd2ProtocolSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}