//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: DriverFatigueProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
// Note: requires additional types generated from: Enums/DriverFatigueSourceTypeProto.proto
// Note: requires additional types generated from: Enums/DriverFatigueReasonTypeProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DriverFatigue")]
  public partial class DriverFatigue : global::ProtoBuf.IExtensible
  {
    public DriverFatigue()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.DriverFatigue,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private DriverFatigueSourceType? _DetectionSource;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"detection_source", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public DriverFatigueSourceType DetectionSource
    {
      get { return _DetectionSource?? DriverFatigueSourceType.DRIVER_FATIGUE_SOURCE_SPEED_MONITORING; }
      set { _DetectionSource = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DetectionSourceSpecified
    {
      get { return this._DetectionSource != null; }
      set { if (value == (this._DetectionSource== null)) this._DetectionSource = value ? this.DetectionSource : (DriverFatigueSourceType?)null; }
    }
    private bool ShouldSerializedetection_source() { return DetectionSourceSpecified; }
    private void Resetdetection_source() { DetectionSourceSpecified = false; }
    
    private DriverFatigueReasonType? _Reason;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public DriverFatigueReasonType Reason
    {
      get { return _Reason?? DriverFatigueReasonType.DRIVER_FATIGUE_REASON_SPEED_UNSPECIFIED; }
      set { _Reason = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ReasonSpecified
    {
      get { return this._Reason != null; }
      set { if (value == (this._Reason== null)) this._Reason = value ? this.Reason : (DriverFatigueReasonType?)null; }
    }
    private bool ShouldSerializereason() { return ReasonSpecified; }
    private void Resetreason() { ReasonSpecified = false; }
    
    private uint? _ContinuousMovingThresholdMinutes;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"continuous_moving_threshold_minutes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ContinuousMovingThresholdMinutes
    {
      get { return _ContinuousMovingThresholdMinutes?? default(uint); }
      set { _ContinuousMovingThresholdMinutes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ContinuousMovingThresholdMinutesSpecified
    {
      get { return this._ContinuousMovingThresholdMinutes != null; }
      set { if (value == (this._ContinuousMovingThresholdMinutes== null)) this._ContinuousMovingThresholdMinutes = value ? this.ContinuousMovingThresholdMinutes : (uint?)null; }
    }
    private bool ShouldSerializecontinuous_moving_threshold_minutes() { return ContinuousMovingThresholdMinutesSpecified; }
    private void Resetcontinuous_moving_threshold_minutes() { ContinuousMovingThresholdMinutesSpecified = false; }
    
    private uint? _MinimumRestThresholdMinutes;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"minimum_rest_threshold_minutes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MinimumRestThresholdMinutes
    {
      get { return _MinimumRestThresholdMinutes?? default(uint); }
      set { _MinimumRestThresholdMinutes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MinimumRestThresholdMinutesSpecified
    {
      get { return this._MinimumRestThresholdMinutes != null; }
      set { if (value == (this._MinimumRestThresholdMinutes== null)) this._MinimumRestThresholdMinutes = value ? this.MinimumRestThresholdMinutes : (uint?)null; }
    }
    private bool ShouldSerializeminimum_rest_threshold_minutes() { return MinimumRestThresholdMinutesSpecified; }
    private void Resetminimum_rest_threshold_minutes() { MinimumRestThresholdMinutesSpecified = false; }
    
    private uint? _MovingSpeedLimit;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"moving_speed_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MovingSpeedLimit
    {
      get { return _MovingSpeedLimit?? default(uint); }
      set { _MovingSpeedLimit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MovingSpeedLimitSpecified
    {
      get { return this._MovingSpeedLimit != null; }
      set { if (value == (this._MovingSpeedLimit== null)) this._MovingSpeedLimit = value ? this.MovingSpeedLimit : (uint?)null; }
    }
    private bool ShouldSerializemoving_speed_limit() { return MovingSpeedLimitSpecified; }
    private void Resetmoving_speed_limit() { MovingSpeedLimitSpecified = false; }
    
    private uint? _DurationOverContinuousMovingThresholdMinutes;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"duration_over_ContinuousMovingThresholdMinutes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint DurationOverContinuousMovingThresholdMinutes
    {
      get { return _DurationOverContinuousMovingThresholdMinutes?? default(uint); }
      set { _DurationOverContinuousMovingThresholdMinutes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DurationOverContinuousMovingThresholdMinutesSpecified
    {
      get { return this._DurationOverContinuousMovingThresholdMinutes != null; }
      set { if (value == (this._DurationOverContinuousMovingThresholdMinutes== null)) this._DurationOverContinuousMovingThresholdMinutes = value ? this.DurationOverContinuousMovingThresholdMinutes : (uint?)null; }
    }
    private bool ShouldSerializeduration_over_ContinuousMovingThresholdMinutes() { return DurationOverContinuousMovingThresholdMinutesSpecified; }
    private void Resetduration_over_ContinuousMovingThresholdMinutes() { DurationOverContinuousMovingThresholdMinutesSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}