//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: DriverRegisteredProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DriverRegistered")]
  public partial class DriverRegistered : global::ProtoBuf.IExtensible
  {
    public DriverRegistered()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.DriverRegistered,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _FleetCode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fleet_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FleetCode
    {
      get { return _FleetCode?? default(uint); }
      set { _FleetCode = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool FleetCodeSpecified
    {
      get { return this._FleetCode != null; }
      set { if (value == (this._FleetCode== null)) this._FleetCode = value ? this.FleetCode : (uint?)null; }
    }
    private bool ShouldSerializefleet_code() { return FleetCodeSpecified; }
    private void Resetfleet_code() { FleetCodeSpecified = false; }
    
    private uint? _VehicleClass;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"vehicle_class", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint VehicleClass
    {
      get { return _VehicleClass?? default(uint); }
      set { _VehicleClass = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool VehicleClassSpecified
    {
      get { return this._VehicleClass != null; }
      set { if (value == (this._VehicleClass== null)) this._VehicleClass = value ? this.VehicleClass : (uint?)null; }
    }
    private bool ShouldSerializevehicle_class() { return VehicleClassSpecified; }
    private void Resetvehicle_class() { VehicleClassSpecified = false; }
    
    private ulong? _DriverId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"driver_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong DriverId
    {
      get { return _DriverId?? default(ulong); }
      set { _DriverId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DriverIdSpecified
    {
      get { return this._DriverId != null; }
      set { if (value == (this._DriverId== null)) this._DriverId = value ? this.DriverId : (ulong?)null; }
    }
    private bool ShouldSerializedriver_id() { return DriverIdSpecified; }
    private void Resetdriver_id() { DriverIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}