//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: EventHeaderProto.proto
// Note: requires additional types generated from: Enums/TripSpeedSourceProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EventHeader")]
  public partial class EventHeader : global::ProtoBuf.IExtensible
  {
    public EventHeader() {}
    
    private uint _TemplateId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"TemplateId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TemplateId
    {
      get { return _TemplateId; }
      set { _TemplateId = value; }
    }
    private string _UnitId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"UnitId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string UnitId
    {
      get { return _UnitId?? ""; }
      set { _UnitId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool UnitIdSpecified
    {
      get { return this._UnitId != null; }
      set { if (value == (this._UnitId== null)) this._UnitId = value ? this.UnitId : (string)null; }
    }
    private bool ShouldSerializeUnitId() { return UnitIdSpecified; }
    private void ResetUnitId() { UnitIdSpecified = false; }
    
    private string _Description;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Description
    {
      get { return _Description?? ""; }
      set { _Description = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DescriptionSpecified
    {
      get { return this._Description != null; }
      set { if (value == (this._Description== null)) this._Description = value ? this.Description : (string)null; }
    }
    private bool ShouldSerializeDescription() { return DescriptionSpecified; }
    private void ResetDescription() { DescriptionSpecified = false; }
    
    private ulong? _UtcTimestampSeconds;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"UtcTimestampSeconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong UtcTimestampSeconds
    {
      get { return _UtcTimestampSeconds?? default(ulong); }
      set { _UtcTimestampSeconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool UtcTimestampSecondsSpecified
    {
      get { return this._UtcTimestampSeconds != null; }
      set { if (value == (this._UtcTimestampSeconds== null)) this._UtcTimestampSeconds = value ? this.UtcTimestampSeconds : (ulong?)null; }
    }
    private bool ShouldSerializeUtcTimestampSeconds() { return UtcTimestampSecondsSpecified; }
    private void ResetUtcTimestampSeconds() { UtcTimestampSecondsSpecified = false; }
    
    private double? _Latitude;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Latitude", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Latitude
    {
      get { return _Latitude?? default(double); }
      set { _Latitude = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool LatitudeSpecified
    {
      get { return this._Latitude != null; }
      set { if (value == (this._Latitude== null)) this._Latitude = value ? this.Latitude : (double?)null; }
    }
    private bool ShouldSerializeLatitude() { return LatitudeSpecified; }
    private void ResetLatitude() { LatitudeSpecified = false; }
    
    private double? _Longitude;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Longitude", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Longitude
    {
      get { return _Longitude?? default(double); }
      set { _Longitude = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool LongitudeSpecified
    {
      get { return this._Longitude != null; }
      set { if (value == (this._Longitude== null)) this._Longitude = value ? this.Longitude : (double?)null; }
    }
    private bool ShouldSerializeLongitude() { return LongitudeSpecified; }
    private void ResetLongitude() { LongitudeSpecified = false; }
    
    private uint? _Speed;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Speed
    {
      get { return _Speed?? default(uint); }
      set { _Speed = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool SpeedSpecified
    {
      get { return this._Speed != null; }
      set { if (value == (this._Speed== null)) this._Speed = value ? this.Speed : (uint?)null; }
    }
    private bool ShouldSerializeSpeed() { return SpeedSpecified; }
    private void ResetSpeed() { SpeedSpecified = false; }
    
    private uint? _Direction;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"Direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Direction
    {
      get { return _Direction?? default(uint); }
      set { _Direction = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DirectionSpecified
    {
      get { return this._Direction != null; }
      set { if (value == (this._Direction== null)) this._Direction = value ? this.Direction : (uint?)null; }
    }
    private bool ShouldSerializeDirection() { return DirectionSpecified; }
    private void ResetDirection() { DirectionSpecified = false; }
    
    private uint? _Odometer;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"Odometer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Odometer
    {
      get { return _Odometer?? default(uint); }
      set { _Odometer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool OdometerSpecified
    {
      get { return this._Odometer != null; }
      set { if (value == (this._Odometer== null)) this._Odometer = value ? this.Odometer : (uint?)null; }
    }
    private bool ShouldSerializeOdometer() { return OdometerSpecified; }
    private void ResetOdometer() { OdometerSpecified = false; }
    
    private uint? _InputStatus;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"InputStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint InputStatus
    {
      get { return _InputStatus?? default(uint); }
      set { _InputStatus = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool InputStatusSpecified
    {
      get { return this._InputStatus != null; }
      set { if (value == (this._InputStatus== null)) this._InputStatus = value ? this.InputStatus : (uint?)null; }
    }
    private bool ShouldSerializeInputStatus() { return InputStatusSpecified; }
    private void ResetInputStatus() { InputStatusSpecified = false; }
    
    private uint? _OutputStatus;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"OutputStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint OutputStatus
    {
      get { return _OutputStatus?? default(uint); }
      set { _OutputStatus = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool OutputStatusSpecified
    {
      get { return this._OutputStatus != null; }
      set { if (value == (this._OutputStatus== null)) this._OutputStatus = value ? this.OutputStatus : (uint?)null; }
    }
    private bool ShouldSerializeOutputStatus() { return OutputStatusSpecified; }
    private void ResetOutputStatus() { OutputStatusSpecified = false; }
    
    private uint? _DriverKeyCode;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"DriverKeyCode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint DriverKeyCode
    {
      get { return _DriverKeyCode?? default(uint); }
      set { _DriverKeyCode = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DriverKeyCodeSpecified
    {
      get { return this._DriverKeyCode != null; }
      set { if (value == (this._DriverKeyCode== null)) this._DriverKeyCode = value ? this.DriverKeyCode : (uint?)null; }
    }
    private bool ShouldSerializeDriverKeyCode() { return DriverKeyCodeSpecified; }
    private void ResetDriverKeyCode() { DriverKeyCodeSpecified = false; }
    
    private uint? _Source;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"Source", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Source
    {
      get { return _Source?? default(uint); }
      set { _Source = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool SourceSpecified
    {
      get { return this._Source != null; }
      set { if (value == (this._Source== null)) this._Source = value ? this.Source : (uint?)null; }
    }
    private bool ShouldSerializeSource() { return SourceSpecified; }
    private void ResetSource() { SourceSpecified = false; }
    
    private uint? _GeneralStatus;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"GeneralStatus", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint GeneralStatus
    {
      get { return _GeneralStatus?? default(uint); }
      set { _GeneralStatus = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool GeneralStatusSpecified
    {
      get { return this._GeneralStatus != null; }
      set { if (value == (this._GeneralStatus== null)) this._GeneralStatus = value ? this.GeneralStatus : (uint?)null; }
    }
    private bool ShouldSerializeGeneralStatus() { return GeneralStatusSpecified; }
    private void ResetGeneralStatus() { GeneralStatusSpecified = false; }
    
    private TripSpeedSource? _TripSpeedSource;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"TripSpeedSource", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public TripSpeedSource TripSpeedSource
    {
      get { return _TripSpeedSource?? TripSpeedSource.TRIP_SPEED_SOURCE_NOT_SUPPORTED; }
      set { _TripSpeedSource = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripSpeedSourceSpecified
    {
      get { return this._TripSpeedSource != null; }
      set { if (value == (this._TripSpeedSource== null)) this._TripSpeedSource = value ? this.TripSpeedSource : (TripSpeedSource?)null; }
    }
    private bool ShouldSerializeTripSpeedSource() { return TripSpeedSourceSpecified; }
    private void ResetTripSpeedSource() { TripSpeedSourceSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}