//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: ExcessiveAccelerationProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExcessiveAcceleration")]
  public partial class ExcessiveAcceleration : global::ProtoBuf.IExtensible
  {
    public ExcessiveAcceleration()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.ExcessiveAcceleration,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _AccelerationLimit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"acceleration_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AccelerationLimit
    {
      get { return _AccelerationLimit?? default(uint); }
      set { _AccelerationLimit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool AccelerationLimitSpecified
    {
      get { return this._AccelerationLimit != null; }
      set { if (value == (this._AccelerationLimit== null)) this._AccelerationLimit = value ? this.AccelerationLimit : (uint?)null; }
    }
    private bool ShouldSerializeacceleration_limit() { return AccelerationLimitSpecified; }
    private void Resetacceleration_limit() { AccelerationLimitSpecified = false; }
    
    private uint? _MaximumAcceleration;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maximum_acceleration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MaximumAcceleration
    {
      get { return _MaximumAcceleration?? default(uint); }
      set { _MaximumAcceleration = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MaximumAccelerationSpecified
    {
      get { return this._MaximumAcceleration != null; }
      set { if (value == (this._MaximumAcceleration== null)) this._MaximumAcceleration = value ? this.MaximumAcceleration : (uint?)null; }
    }
    private bool ShouldSerializemaximum_acceleration() { return MaximumAccelerationSpecified; }
    private void Resetmaximum_acceleration() { MaximumAccelerationSpecified = false; }
    
    private uint? _DurationSeconds;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"duration_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint DurationSeconds
    {
      get { return _DurationSeconds?? default(uint); }
      set { _DurationSeconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DurationSecondsSpecified
    {
      get { return this._DurationSeconds != null; }
      set { if (value == (this._DurationSeconds== null)) this._DurationSeconds = value ? this.DurationSeconds : (uint?)null; }
    }
    private bool ShouldSerializeduration_seconds() { return DurationSecondsSpecified; }
    private void Resetduration_seconds() { DurationSecondsSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}