//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: ExcessiveRpmProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExcessiveRpm")]
  public partial class ExcessiveRpm : global::ProtoBuf.IExtensible
  {
    public ExcessiveRpm()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.ExcessiveRpm,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _RpmLimit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rpm_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RpmLimit
    {
      get { return _RpmLimit?? default(uint); }
      set { _RpmLimit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool RpmLimitSpecified
    {
      get { return this._RpmLimit != null; }
      set { if (value == (this._RpmLimit== null)) this._RpmLimit = value ? this.RpmLimit : (uint?)null; }
    }
    private bool ShouldSerializerpm_limit() { return RpmLimitSpecified; }
    private void Resetrpm_limit() { RpmLimitSpecified = false; }
    
    private uint? _MaximumRpm;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maximum_rpm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MaximumRpm
    {
      get { return _MaximumRpm?? default(uint); }
      set { _MaximumRpm = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MaximumRpmSpecified
    {
      get { return this._MaximumRpm != null; }
      set { if (value == (this._MaximumRpm== null)) this._MaximumRpm = value ? this.MaximumRpm : (uint?)null; }
    }
    private bool ShouldSerializemaximum_rpm() { return MaximumRpmSpecified; }
    private void Resetmaximum_rpm() { MaximumRpmSpecified = false; }
    
    private uint? _DurationSeconds;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"duration_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint DurationSeconds
    {
      get { return _DurationSeconds?? default(uint); }
      set { _DurationSeconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DurationSecondsSpecified
    {
      get { return this._DurationSeconds != null; }
      set { if (value == (this._DurationSeconds== null)) this._DurationSeconds = value ? this.DurationSeconds : (uint?)null; }
    }
    private bool ShouldSerializeduration_seconds() { return DurationSecondsSpecified; }
    private void Resetduration_seconds() { DurationSecondsSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}