//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: FacilityStatusProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FacilityStatus")]
  public partial class FacilityStatus : global::ProtoBuf.IExtensible
  {
    public FacilityStatus()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.FacilityStatus,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _Rpm;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rpm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Rpm
    {
      get { return _Rpm?? default(uint); }
      set { _Rpm = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool RpmSpecified
    {
      get { return this._Rpm != null; }
      set { if (value == (this._Rpm== null)) this._Rpm = value ? this.Rpm : (uint?)null; }
    }
    private bool ShouldSerializerpm() { return RpmSpecified; }
    private void Resetrpm() { RpmSpecified = false; }
    
    private float? _FuelLevelPercentage;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fuel_level_percentage", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float FuelLevelPercentage
    {
      get { return _FuelLevelPercentage?? default(float); }
      set { _FuelLevelPercentage = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool FuelLevelPercentageSpecified
    {
      get { return this._FuelLevelPercentage != null; }
      set { if (value == (this._FuelLevelPercentage== null)) this._FuelLevelPercentage = value ? this.FuelLevelPercentage : (float?)null; }
    }
    private bool ShouldSerializefuel_level_percentage() { return FuelLevelPercentageSpecified; }
    private void Resetfuel_level_percentage() { FuelLevelPercentageSpecified = false; }
    
    private float? _Voltage;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"voltage", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Voltage
    {
      get { return _Voltage?? default(float); }
      set { _Voltage = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool VoltageSpecified
    {
      get { return this._Voltage != null; }
      set { if (value == (this._Voltage== null)) this._Voltage = value ? this.Voltage : (float?)null; }
    }
    private bool ShouldSerializevoltage() { return VoltageSpecified; }
    private void Resetvoltage() { VoltageSpecified = false; }
    
    private uint? _FlowMeter;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"flow_meter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FlowMeter
    {
      get { return _FlowMeter?? default(uint); }
      set { _FlowMeter = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool FlowMeterSpecified
    {
      get { return this._FlowMeter != null; }
      set { if (value == (this._FlowMeter== null)) this._FlowMeter = value ? this.FlowMeter : (uint?)null; }
    }
    private bool ShouldSerializeflow_meter() { return FlowMeterSpecified; }
    private void Resetflow_meter() { FlowMeterSpecified = false; }
    
    private float? _Temperature1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"temperature_1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Temperature1
    {
      get { return _Temperature1?? default(float); }
      set { _Temperature1 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Temperature1Specified
    {
      get { return this._Temperature1 != null; }
      set { if (value == (this._Temperature1== null)) this._Temperature1 = value ? this.Temperature1 : (float?)null; }
    }
    private bool ShouldSerializetemperature_1() { return Temperature1Specified; }
    private void Resettemperature_1() { Temperature1Specified = false; }
    
    private float? _Temperature2;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"temperature_2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Temperature2
    {
      get { return _Temperature2?? default(float); }
      set { _Temperature2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Temperature2Specified
    {
      get { return this._Temperature2 != null; }
      set { if (value == (this._Temperature2== null)) this._Temperature2 = value ? this.Temperature2 : (float?)null; }
    }
    private bool ShouldSerializetemperature_2() { return Temperature2Specified; }
    private void Resettemperature_2() { Temperature2Specified = false; }
    
    private uint? _Analog1;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"analog_1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Analog1
    {
      get { return _Analog1?? default(uint); }
      set { _Analog1 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Analog1Specified
    {
      get { return this._Analog1 != null; }
      set { if (value == (this._Analog1== null)) this._Analog1 = value ? this.Analog1 : (uint?)null; }
    }
    private bool ShouldSerializeanalog_1() { return Analog1Specified; }
    private void Resetanalog_1() { Analog1Specified = false; }
    
    private uint? _Analog2;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"analog_2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Analog2
    {
      get { return _Analog2?? default(uint); }
      set { _Analog2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Analog2Specified
    {
      get { return this._Analog2 != null; }
      set { if (value == (this._Analog2== null)) this._Analog2 = value ? this.Analog2 : (uint?)null; }
    }
    private bool ShouldSerializeanalog_2() { return Analog2Specified; }
    private void Resetanalog_2() { Analog2Specified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}