//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: FMSDataProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FMSData")]
  public partial class FMSData : global::ProtoBuf.IExtensible
  {
    public FMSData()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.FMSData,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _CanTripDistance;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"can_trip_distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CanTripDistance
    {
      get { return _CanTripDistance?? default(uint); }
      set { _CanTripDistance = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool CanTripDistanceSpecified
    {
      get { return this._CanTripDistance != null; }
      set { if (value == (this._CanTripDistance== null)) this._CanTripDistance = value ? this.CanTripDistance : (uint?)null; }
    }
    private bool ShouldSerializecan_trip_distance() { return CanTripDistanceSpecified; }
    private void Resetcan_trip_distance() { CanTripDistanceSpecified = false; }
    
    private uint? _FuelLevel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"fuel_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FuelLevel
    {
      get { return _FuelLevel?? default(uint); }
      set { _FuelLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool FuelLevelSpecified
    {
      get { return this._FuelLevel != null; }
      set { if (value == (this._FuelLevel== null)) this._FuelLevel = value ? this.FuelLevel : (uint?)null; }
    }
    private bool ShouldSerializefuel_level() { return FuelLevelSpecified; }
    private void Resetfuel_level() { FuelLevelSpecified = false; }
    
    private uint? _TotalFuel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"total_fuel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TotalFuel
    {
      get { return _TotalFuel?? default(uint); }
      set { _TotalFuel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TotalFuelSpecified
    {
      get { return this._TotalFuel != null; }
      set { if (value == (this._TotalFuel== null)) this._TotalFuel = value ? this.TotalFuel : (uint?)null; }
    }
    private bool ShouldSerializetotal_fuel() { return TotalFuelSpecified; }
    private void Resettotal_fuel() { TotalFuelSpecified = false; }
    
    private uint? _FmsTco;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fms_tco", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FmsTco
    {
      get { return _FmsTco?? default(uint); }
      set { _FmsTco = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool FmsTcoSpecified
    {
      get { return this._FmsTco != null; }
      set { if (value == (this._FmsTco== null)) this._FmsTco = value ? this.FmsTco : (uint?)null; }
    }
    private bool ShouldSerializefms_tco() { return FmsTcoSpecified; }
    private void Resetfms_tco() { FmsTcoSpecified = false; }
    
    private uint? _FmsAxleWeight1;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fms_axle_weight1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FmsAxleWeight1
    {
      get { return _FmsAxleWeight1?? default(uint); }
      set { _FmsAxleWeight1 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool FmsAxleWeight1Specified
    {
      get { return this._FmsAxleWeight1 != null; }
      set { if (value == (this._FmsAxleWeight1== null)) this._FmsAxleWeight1 = value ? this.FmsAxleWeight1 : (uint?)null; }
    }
    private bool ShouldSerializefms_axle_weight1() { return FmsAxleWeight1Specified; }
    private void Resetfms_axle_weight1() { FmsAxleWeight1Specified = false; }
    
    private uint? _FmsAxleWeight2;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fms_axle_weight2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint FmsAxleWeight2
    {
      get { return _FmsAxleWeight2?? default(uint); }
      set { _FmsAxleWeight2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool FmsAxleWeight2Specified
    {
      get { return this._FmsAxleWeight2 != null; }
      set { if (value == (this._FmsAxleWeight2== null)) this._FmsAxleWeight2 = value ? this.FmsAxleWeight2 : (uint?)null; }
    }
    private bool ShouldSerializefms_axle_weight2() { return FmsAxleWeight2Specified; }
    private void Resetfms_axle_weight2() { FmsAxleWeight2Specified = false; }
    
    private uint? _TotalEngineHours;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"total_engine_hours", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TotalEngineHours
    {
      get { return _TotalEngineHours?? default(uint); }
      set { _TotalEngineHours = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TotalEngineHoursSpecified
    {
      get { return this._TotalEngineHours != null; }
      set { if (value == (this._TotalEngineHours== null)) this._TotalEngineHours = value ? this.TotalEngineHours : (uint?)null; }
    }
    private bool ShouldSerializetotal_engine_hours() { return TotalEngineHoursSpecified; }
    private void Resettotal_engine_hours() { TotalEngineHoursSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}