//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: GeoHotSpotEntryProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GeoHotSpotEntry")]
  public partial class GeoHotSpotEntry : global::ProtoBuf.IExtensible
  {
    public GeoHotSpotEntry()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.GeoHotSpotEntry,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _ReferenceId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reference_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ReferenceId
    {
      get { return _ReferenceId?? default(uint); }
      set { _ReferenceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ReferenceIdSpecified
    {
      get { return this._ReferenceId != null; }
      set { if (value == (this._ReferenceId== null)) this._ReferenceId = value ? this.ReferenceId : (uint?)null; }
    }
    private bool ShouldSerializereference_id() { return ReferenceIdSpecified; }
    private void Resetreference_id() { ReferenceIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}