//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: GsmNoticeGsmPositionInfoDataProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GsmNoticeGsmPositionInfoData")]
  public partial class GsmNoticeGsmPositionInfoData : global::ProtoBuf.IExtensible
  {
    public GsmNoticeGsmPositionInfoData() {}
    
    private byte[] _Data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] Data
    {
      get { return _Data?? null; }
      set { _Data = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DataSpecified
    {
      get { return this._Data != null; }
      set { if (value == (this._Data== null)) this._Data = value ? this.Data : (byte[])null; }
    }
    private bool ShouldSerializedata() { return DataSpecified; }
    private void Resetdata() { DataSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}