//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: GsmNoticeGsmJammingDataProto.proto
// Note: requires additional types generated from: Enums/GsmNoticeGsmJammingStatusTypeProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GsmNoticeGsmJammingData")]
  public partial class GsmNoticeGsmJammingData : global::ProtoBuf.IExtensible
  {
    public GsmNoticeGsmJammingData() {}
    
    private uint? _JammingStatus;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"jamming_status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint JammingStatus
    {
      get { return _JammingStatus?? default(uint); }
      set { _JammingStatus = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool JammingStatusSpecified
    {
      get { return this._JammingStatus != null; }
      set { if (value == (this._JammingStatus== null)) this._JammingStatus = value ? this.JammingStatus : (uint?)null; }
    }
    private bool ShouldSerializejamming_status() { return JammingStatusSpecified; }
    private void Resetjamming_status() { JammingStatusSpecified = false; }
    
    private uint? _ConfiguredNoisePowerLevel;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"configured_noise_power_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ConfiguredNoisePowerLevel
    {
      get { return _ConfiguredNoisePowerLevel?? default(uint); }
      set { _ConfiguredNoisePowerLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ConfiguredNoisePowerLevelSpecified
    {
      get { return this._ConfiguredNoisePowerLevel != null; }
      set { if (value == (this._ConfiguredNoisePowerLevel== null)) this._ConfiguredNoisePowerLevel = value ? this.ConfiguredNoisePowerLevel : (uint?)null; }
    }
    private bool ShouldSerializeconfigured_noise_power_level() { return ConfiguredNoisePowerLevelSpecified; }
    private void Resetconfigured_noise_power_level() { ConfiguredNoisePowerLevelSpecified = false; }
    
    private uint? _ConfiguredMinimumJammedChannel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"configured_minimum_jammed_channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ConfiguredMinimumJammedChannel
    {
      get { return _ConfiguredMinimumJammedChannel?? default(uint); }
      set { _ConfiguredMinimumJammedChannel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ConfiguredMinimumJammedChannelSpecified
    {
      get { return this._ConfiguredMinimumJammedChannel != null; }
      set { if (value == (this._ConfiguredMinimumJammedChannel== null)) this._ConfiguredMinimumJammedChannel = value ? this.ConfiguredMinimumJammedChannel : (uint?)null; }
    }
    private bool ShouldSerializeconfigured_minimum_jammed_channel() { return ConfiguredMinimumJammedChannelSpecified; }
    private void Resetconfigured_minimum_jammed_channel() { ConfiguredMinimumJammedChannelSpecified = false; }
    
    private uint? _ConfiguredJammingDetectNotificationLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"configured_jamming_detect_notification_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ConfiguredJammingDetectNotificationLevel
    {
      get { return _ConfiguredJammingDetectNotificationLevel?? default(uint); }
      set { _ConfiguredJammingDetectNotificationLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ConfiguredJammingDetectNotificationLevelSpecified
    {
      get { return this._ConfiguredJammingDetectNotificationLevel != null; }
      set { if (value == (this._ConfiguredJammingDetectNotificationLevel== null)) this._ConfiguredJammingDetectNotificationLevel = value ? this.ConfiguredJammingDetectNotificationLevel : (uint?)null; }
    }
    private bool ShouldSerializeconfigured_jamming_detect_notification_level() { return ConfiguredJammingDetectNotificationLevelSpecified; }
    private void Resetconfigured_jamming_detect_notification_level() { ConfiguredJammingDetectNotificationLevelSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}