//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: GsmNoticeImsiChangeDataProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GsmNoticeImsiChangeData")]
  public partial class GsmNoticeImsiChangeData : global::ProtoBuf.IExtensible
  {
    public GsmNoticeImsiChangeData() {}
    
    private string _Imsi;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"imsi", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Imsi
    {
      get { return _Imsi?? ""; }
      set { _Imsi = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ImsiSpecified
    {
      get { return this._Imsi != null; }
      set { if (value == (this._Imsi== null)) this._Imsi = value ? this.Imsi : (string)null; }
    }
    private bool ShouldSerializeimsi() { return ImsiSpecified; }
    private void Resetimsi() { ImsiSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}