//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: GsmNoticeMobileNetworkDataProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GsmNoticeMobileNetworkData")]
  public partial class GsmNoticeMobileNetworkData : global::ProtoBuf.IExtensible
  {
    public GsmNoticeMobileNetworkData() {}
    
    private uint? _Mnc;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mnc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Mnc
    {
      get { return _Mnc?? default(uint); }
      set { _Mnc = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MncSpecified
    {
      get { return this._Mnc != null; }
      set { if (value == (this._Mnc== null)) this._Mnc = value ? this.Mnc : (uint?)null; }
    }
    private bool ShouldSerializemnc() { return MncSpecified; }
    private void Resetmnc() { MncSpecified = false; }
    
    private uint? _Mcc;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mcc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Mcc
    {
      get { return _Mcc?? default(uint); }
      set { _Mcc = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MccSpecified
    {
      get { return this._Mcc != null; }
      set { if (value == (this._Mcc== null)) this._Mcc = value ? this.Mcc : (uint?)null; }
    }
    private bool ShouldSerializemcc() { return MccSpecified; }
    private void Resetmcc() { MccSpecified = false; }
    
    private uint? _ScLac;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sc_lac", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ScLac
    {
      get { return _ScLac?? default(uint); }
      set { _ScLac = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ScLacSpecified
    {
      get { return this._ScLac != null; }
      set { if (value == (this._ScLac== null)) this._ScLac = value ? this.ScLac : (uint?)null; }
    }
    private bool ShouldSerializesc_lac() { return ScLacSpecified; }
    private void Resetsc_lac() { ScLacSpecified = false; }
    
    private uint? _ScCid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sc_cid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ScCid
    {
      get { return _ScCid?? default(uint); }
      set { _ScCid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ScCidSpecified
    {
      get { return this._ScCid != null; }
      set { if (value == (this._ScCid== null)) this._ScCid = value ? this.ScCid : (uint?)null; }
    }
    private bool ShouldSerializesc_cid() { return ScCidSpecified; }
    private void Resetsc_cid() { ScCidSpecified = false; }
    
    private int? _ScDbm;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sc_dbm", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int ScDbm
    {
      get { return _ScDbm?? default(int); }
      set { _ScDbm = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ScDbmSpecified
    {
      get { return this._ScDbm != null; }
      set { if (value == (this._ScDbm== null)) this._ScDbm = value ? this.ScDbm : (int?)null; }
    }
    private bool ShouldSerializesc_dbm() { return ScDbmSpecified; }
    private void Resetsc_dbm() { ScDbmSpecified = false; }
    
    private uint? _ScRssi;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"sc_rssi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ScRssi
    {
      get { return _ScRssi?? default(uint); }
      set { _ScRssi = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ScRssiSpecified
    {
      get { return this._ScRssi != null; }
      set { if (value == (this._ScRssi== null)) this._ScRssi = value ? this.ScRssi : (uint?)null; }
    }
    private bool ShouldSerializesc_rssi() { return ScRssiSpecified; }
    private void Resetsc_rssi() { ScRssiSpecified = false; }
    
    private uint? _Nc1Lac;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"nc1_lac", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Nc1Lac
    {
      get { return _Nc1Lac?? default(uint); }
      set { _Nc1Lac = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Nc1LacSpecified
    {
      get { return this._Nc1Lac != null; }
      set { if (value == (this._Nc1Lac== null)) this._Nc1Lac = value ? this.Nc1Lac : (uint?)null; }
    }
    private bool ShouldSerializenc1_lac() { return Nc1LacSpecified; }
    private void Resetnc1_lac() { Nc1LacSpecified = false; }
    
    private uint? _Nc1Cid;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"nc1_cid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Nc1Cid
    {
      get { return _Nc1Cid?? default(uint); }
      set { _Nc1Cid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Nc1CidSpecified
    {
      get { return this._Nc1Cid != null; }
      set { if (value == (this._Nc1Cid== null)) this._Nc1Cid = value ? this.Nc1Cid : (uint?)null; }
    }
    private bool ShouldSerializenc1_cid() { return Nc1CidSpecified; }
    private void Resetnc1_cid() { Nc1CidSpecified = false; }
    
    private int? _Nc1Dbm;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"nc1_dbm", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Nc1Dbm
    {
      get { return _Nc1Dbm?? default(int); }
      set { _Nc1Dbm = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Nc1DbmSpecified
    {
      get { return this._Nc1Dbm != null; }
      set { if (value == (this._Nc1Dbm== null)) this._Nc1Dbm = value ? this.Nc1Dbm : (int?)null; }
    }
    private bool ShouldSerializenc1_dbm() { return Nc1DbmSpecified; }
    private void Resetnc1_dbm() { Nc1DbmSpecified = false; }
    
    private uint? _Nc1Rssi;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"nc1_rssi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Nc1Rssi
    {
      get { return _Nc1Rssi?? default(uint); }
      set { _Nc1Rssi = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Nc1RssiSpecified
    {
      get { return this._Nc1Rssi != null; }
      set { if (value == (this._Nc1Rssi== null)) this._Nc1Rssi = value ? this.Nc1Rssi : (uint?)null; }
    }
    private bool ShouldSerializenc1_rssi() { return Nc1RssiSpecified; }
    private void Resetnc1_rssi() { Nc1RssiSpecified = false; }
    
    private uint? _Nc2Lac;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"nc2_lac", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Nc2Lac
    {
      get { return _Nc2Lac?? default(uint); }
      set { _Nc2Lac = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Nc2LacSpecified
    {
      get { return this._Nc2Lac != null; }
      set { if (value == (this._Nc2Lac== null)) this._Nc2Lac = value ? this.Nc2Lac : (uint?)null; }
    }
    private bool ShouldSerializenc2_lac() { return Nc2LacSpecified; }
    private void Resetnc2_lac() { Nc2LacSpecified = false; }
    
    private uint? _Nc2Cid;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"nc2_cid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Nc2Cid
    {
      get { return _Nc2Cid?? default(uint); }
      set { _Nc2Cid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Nc2CidSpecified
    {
      get { return this._Nc2Cid != null; }
      set { if (value == (this._Nc2Cid== null)) this._Nc2Cid = value ? this.Nc2Cid : (uint?)null; }
    }
    private bool ShouldSerializenc2_cid() { return Nc2CidSpecified; }
    private void Resetnc2_cid() { Nc2CidSpecified = false; }
    
    private int? _Nc2Dbm;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"nc2_dbm", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Nc2Dbm
    {
      get { return _Nc2Dbm?? default(int); }
      set { _Nc2Dbm = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Nc2DbmSpecified
    {
      get { return this._Nc2Dbm != null; }
      set { if (value == (this._Nc2Dbm== null)) this._Nc2Dbm = value ? this.Nc2Dbm : (int?)null; }
    }
    private bool ShouldSerializenc2_dbm() { return Nc2DbmSpecified; }
    private void Resetnc2_dbm() { Nc2DbmSpecified = false; }
    
    private uint? _Nc2Rssi;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"nc2_rssi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Nc2Rssi
    {
      get { return _Nc2Rssi?? default(uint); }
      set { _Nc2Rssi = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Nc2RssiSpecified
    {
      get { return this._Nc2Rssi != null; }
      set { if (value == (this._Nc2Rssi== null)) this._Nc2Rssi = value ? this.Nc2Rssi : (uint?)null; }
    }
    private bool ShouldSerializenc2_rssi() { return Nc2RssiSpecified; }
    private void Resetnc2_rssi() { Nc2RssiSpecified = false; }
    
    private uint? _Nc3Lac;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"nc3_lac", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Nc3Lac
    {
      get { return _Nc3Lac?? default(uint); }
      set { _Nc3Lac = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Nc3LacSpecified
    {
      get { return this._Nc3Lac != null; }
      set { if (value == (this._Nc3Lac== null)) this._Nc3Lac = value ? this.Nc3Lac : (uint?)null; }
    }
    private bool ShouldSerializenc3_lac() { return Nc3LacSpecified; }
    private void Resetnc3_lac() { Nc3LacSpecified = false; }
    
    private uint? _Nc3Cid;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"nc3_cid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Nc3Cid
    {
      get { return _Nc3Cid?? default(uint); }
      set { _Nc3Cid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Nc3CidSpecified
    {
      get { return this._Nc3Cid != null; }
      set { if (value == (this._Nc3Cid== null)) this._Nc3Cid = value ? this.Nc3Cid : (uint?)null; }
    }
    private bool ShouldSerializenc3_cid() { return Nc3CidSpecified; }
    private void Resetnc3_cid() { Nc3CidSpecified = false; }
    
    private int? _Nc3Dbm;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"nc3_dbm", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Nc3Dbm
    {
      get { return _Nc3Dbm?? default(int); }
      set { _Nc3Dbm = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Nc3DbmSpecified
    {
      get { return this._Nc3Dbm != null; }
      set { if (value == (this._Nc3Dbm== null)) this._Nc3Dbm = value ? this.Nc3Dbm : (int?)null; }
    }
    private bool ShouldSerializenc3_dbm() { return Nc3DbmSpecified; }
    private void Resetnc3_dbm() { Nc3DbmSpecified = false; }
    
    private uint? _Nc3Rssi;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"nc3_rssi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Nc3Rssi
    {
      get { return _Nc3Rssi?? default(uint); }
      set { _Nc3Rssi = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Nc3RssiSpecified
    {
      get { return this._Nc3Rssi != null; }
      set { if (value == (this._Nc3Rssi== null)) this._Nc3Rssi = value ? this.Nc3Rssi : (uint?)null; }
    }
    private bool ShouldSerializenc3_rssi() { return Nc3RssiSpecified; }
    private void Resetnc3_rssi() { Nc3RssiSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}