//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: GsmNoticeProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
// Note: requires additional types generated from: Enums/GsmNoticeTypeProto.proto
// Note: requires additional types generated from: GsmNoticeImsiChangeDataProto.proto
// Note: requires additional types generated from: GsmNoticeMobileNetworkDataProto.proto
// Note: requires additional types generated from: GsmNoticeGsmPositionInfoDataProto.proto
// Note: requires additional types generated from: GsmNoticeGsmJammingDataProto.proto
// Note: requires additional types generated from: GsmNoticeMobileImsiDataProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GsmNotice")]
  public partial class GsmNotice : global::ProtoBuf.IExtensible
  {
    public GsmNotice()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.GsmNotice,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private GsmNoticeType? _NoticeType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"notice_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public GsmNoticeType NoticeType
    {
      get { return _NoticeType?? GsmNoticeType.GSM_NOTICE_UNDEFINED; }
      set { _NoticeType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool NoticeTypeSpecified
    {
      get { return this._NoticeType != null; }
      set { if (value == (this._NoticeType== null)) this._NoticeType = value ? this.NoticeType : (GsmNoticeType?)null; }
    }
    private bool ShouldSerializenotice_type() { return NoticeTypeSpecified; }
    private void Resetnotice_type() { NoticeTypeSpecified = false; }
    
    private GsmNoticeImsiChangeData _ImsiChangeData = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"imsi_change_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GsmNoticeImsiChangeData ImsiChangeData
    {
      get { return _ImsiChangeData; }
      set { _ImsiChangeData = value; }
    }
    private GsmNoticeMobileNetworkData _MobileNetworkData = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mobile_network_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GsmNoticeMobileNetworkData MobileNetworkData
    {
      get { return _MobileNetworkData; }
      set { _MobileNetworkData = value; }
    }
    private GsmNoticeGsmPositionInfoData _GsmPositionInfoData = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"gsm_position_info_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GsmNoticeGsmPositionInfoData GsmPositionInfoData
    {
      get { return _GsmPositionInfoData; }
      set { _GsmPositionInfoData = value; }
    }
    private GsmNoticeGsmJammingData _GsmJammingData = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"gsm_jamming_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GsmNoticeGsmJammingData GsmJammingData
    {
      get { return _GsmJammingData; }
      set { _GsmJammingData = value; }
    }
    private GsmNoticeMobileImsiData _MobileImsiData = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"mobile_imsi_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public GsmNoticeMobileImsiData MobileImsiData
    {
      get { return _MobileImsiData; }
      set { _MobileImsiData = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}