//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: HarshBrakingProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HarshBraking")]
  public partial class HarshBraking : global::ProtoBuf.IExtensible
  {
    public HarshBraking()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.HarshBraking,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _BrakingLimit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"braking_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BrakingLimit
    {
      get { return _BrakingLimit?? default(uint); }
      set { _BrakingLimit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool BrakingLimitSpecified
    {
      get { return this._BrakingLimit != null; }
      set { if (value == (this._BrakingLimit== null)) this._BrakingLimit = value ? this.BrakingLimit : (uint?)null; }
    }
    private bool ShouldSerializebraking_limit() { return BrakingLimitSpecified; }
    private void Resetbraking_limit() { BrakingLimitSpecified = false; }
    
    private uint? _MaximumBraking;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maximum_braking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MaximumBraking
    {
      get { return _MaximumBraking?? default(uint); }
      set { _MaximumBraking = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MaximumBrakingSpecified
    {
      get { return this._MaximumBraking != null; }
      set { if (value == (this._MaximumBraking== null)) this._MaximumBraking = value ? this.MaximumBraking : (uint?)null; }
    }
    private bool ShouldSerializemaximum_braking() { return MaximumBrakingSpecified; }
    private void Resetmaximum_braking() { MaximumBrakingSpecified = false; }
    
    private uint? _DurationSeconds;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"duration_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint DurationSeconds
    {
      get { return _DurationSeconds?? default(uint); }
      set { _DurationSeconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DurationSecondsSpecified
    {
      get { return this._DurationSeconds != null; }
      set { if (value == (this._DurationSeconds== null)) this._DurationSeconds = value ? this.DurationSeconds : (uint?)null; }
    }
    private bool ShouldSerializeduration_seconds() { return DurationSecondsSpecified; }
    private void Resetduration_seconds() { DurationSecondsSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}