//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: HealthMetricsProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HealthMetrics")]
  public partial class HealthMetrics : global::ProtoBuf.IExtensible
  {
    public HealthMetrics()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.HealthMetrics,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _BytesSent;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bytes_sent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BytesSent
    {
      get { return _BytesSent?? default(uint); }
      set { _BytesSent = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool BytesSentSpecified
    {
      get { return this._BytesSent != null; }
      set { if (value == (this._BytesSent== null)) this._BytesSent = value ? this.BytesSent : (uint?)null; }
    }
    private bool ShouldSerializebytes_sent() { return BytesSentSpecified; }
    private void Resetbytes_sent() { BytesSentSpecified = false; }
    
    private uint? _BytesReceived;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bytes_received", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint BytesReceived
    {
      get { return _BytesReceived?? default(uint); }
      set { _BytesReceived = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool BytesReceivedSpecified
    {
      get { return this._BytesReceived != null; }
      set { if (value == (this._BytesReceived== null)) this._BytesReceived = value ? this.BytesReceived : (uint?)null; }
    }
    private bool ShouldSerializebytes_received() { return BytesReceivedSpecified; }
    private void Resetbytes_received() { BytesReceivedSpecified = false; }
    
    private uint? _SmsSent;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"sms_sent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SmsSent
    {
      get { return _SmsSent?? default(uint); }
      set { _SmsSent = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool SmsSentSpecified
    {
      get { return this._SmsSent != null; }
      set { if (value == (this._SmsSent== null)) this._SmsSent = value ? this.SmsSent : (uint?)null; }
    }
    private bool ShouldSerializesms_sent() { return SmsSentSpecified; }
    private void Resetsms_sent() { SmsSentSpecified = false; }
    
    private uint? _TripGpsLockPercent;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"trip_gps_lock_percent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TripGpsLockPercent
    {
      get { return _TripGpsLockPercent?? default(uint); }
      set { _TripGpsLockPercent = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripGpsLockPercentSpecified
    {
      get { return this._TripGpsLockPercent != null; }
      set { if (value == (this._TripGpsLockPercent== null)) this._TripGpsLockPercent = value ? this.TripGpsLockPercent : (uint?)null; }
    }
    private bool ShouldSerializetrip_gps_lock_percent() { return TripGpsLockPercentSpecified; }
    private void Resettrip_gps_lock_percent() { TripGpsLockPercentSpecified = false; }
    
    private uint? _TripObd2LockPercent;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"trip_obd2_lock_percent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TripObd2LockPercent
    {
      get { return _TripObd2LockPercent?? default(uint); }
      set { _TripObd2LockPercent = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripObd2LockPercentSpecified
    {
      get { return this._TripObd2LockPercent != null; }
      set { if (value == (this._TripObd2LockPercent== null)) this._TripObd2LockPercent = value ? this.TripObd2LockPercent : (uint?)null; }
    }
    private bool ShouldSerializetrip_obd2_lock_percent() { return TripObd2LockPercentSpecified; }
    private void Resettrip_obd2_lock_percent() { TripObd2LockPercentSpecified = false; }
    
    private uint? _AverageRssi;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"average_rssi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AverageRssi
    {
      get { return _AverageRssi?? default(uint); }
      set { _AverageRssi = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool AverageRssiSpecified
    {
      get { return this._AverageRssi != null; }
      set { if (value == (this._AverageRssi== null)) this._AverageRssi = value ? this.AverageRssi : (uint?)null; }
    }
    private bool ShouldSerializeaverage_rssi() { return AverageRssiSpecified; }
    private void Resetaverage_rssi() { AverageRssiSpecified = false; }
    
    private uint? _AverageTemperature;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"average_temperature", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AverageTemperature
    {
      get { return _AverageTemperature?? default(uint); }
      set { _AverageTemperature = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool AverageTemperatureSpecified
    {
      get { return this._AverageTemperature != null; }
      set { if (value == (this._AverageTemperature== null)) this._AverageTemperature = value ? this.AverageTemperature : (uint?)null; }
    }
    private bool ShouldSerializeaverage_temperature() { return AverageTemperatureSpecified; }
    private void Resetaverage_temperature() { AverageTemperatureSpecified = false; }
    
    private uint? _MaxTemperature;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"max_temperature", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MaxTemperature
    {
      get { return _MaxTemperature?? default(uint); }
      set { _MaxTemperature = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MaxTemperatureSpecified
    {
      get { return this._MaxTemperature != null; }
      set { if (value == (this._MaxTemperature== null)) this._MaxTemperature = value ? this.MaxTemperature : (uint?)null; }
    }
    private bool ShouldSerializemax_temperature() { return MaxTemperatureSpecified; }
    private void Resetmax_temperature() { MaxTemperatureSpecified = false; }
    
    private float? _BatteryVoltage;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"battery_voltage", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float BatteryVoltage
    {
      get { return _BatteryVoltage?? default(float); }
      set { _BatteryVoltage = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool BatteryVoltageSpecified
    {
      get { return this._BatteryVoltage != null; }
      set { if (value == (this._BatteryVoltage== null)) this._BatteryVoltage = value ? this.BatteryVoltage : (float?)null; }
    }
    private bool ShouldSerializebattery_voltage() { return BatteryVoltageSpecified; }
    private void Resetbattery_voltage() { BatteryVoltageSpecified = false; }
    
    private float? _VehicleVoltage;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"vehicle_voltage", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float VehicleVoltage
    {
      get { return _VehicleVoltage?? default(float); }
      set { _VehicleVoltage = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool VehicleVoltageSpecified
    {
      get { return this._VehicleVoltage != null; }
      set { if (value == (this._VehicleVoltage== null)) this._VehicleVoltage = value ? this.VehicleVoltage : (float?)null; }
    }
    private bool ShouldSerializevehicle_voltage() { return VehicleVoltageSpecified; }
    private void Resetvehicle_voltage() { VehicleVoltageSpecified = false; }
    
    private uint? _EventIndex;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"event_index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint EventIndex
    {
      get { return _EventIndex?? default(uint); }
      set { _EventIndex = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool EventIndexSpecified
    {
      get { return this._EventIndex != null; }
      set { if (value == (this._EventIndex== null)) this._EventIndex = value ? this.EventIndex : (uint?)null; }
    }
    private bool ShouldSerializeevent_index() { return EventIndexSpecified; }
    private void Resetevent_index() { EventIndexSpecified = false; }
    
    private uint? _ModemRebootsCount;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"modem_reboots_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ModemRebootsCount
    {
      get { return _ModemRebootsCount?? default(uint); }
      set { _ModemRebootsCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ModemRebootsCountSpecified
    {
      get { return this._ModemRebootsCount != null; }
      set { if (value == (this._ModemRebootsCount== null)) this._ModemRebootsCount = value ? this.ModemRebootsCount : (uint?)null; }
    }
    private bool ShouldSerializemodem_reboots_count() { return ModemRebootsCountSpecified; }
    private void Resetmodem_reboots_count() { ModemRebootsCountSpecified = false; }
    
    private uint? _Flags;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"flags", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Flags
    {
      get { return _Flags?? default(uint); }
      set { _Flags = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool FlagsSpecified
    {
      get { return this._Flags != null; }
      set { if (value == (this._Flags== null)) this._Flags = value ? this.Flags : (uint?)null; }
    }
    private bool ShouldSerializeflags() { return FlagsSpecified; }
    private void Resetflags() { FlagsSpecified = false; }
    
    private uint? _UnitRebootsCount;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"unit_reboots_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint UnitRebootsCount
    {
      get { return _UnitRebootsCount?? default(uint); }
      set { _UnitRebootsCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool UnitRebootsCountSpecified
    {
      get { return this._UnitRebootsCount != null; }
      set { if (value == (this._UnitRebootsCount== null)) this._UnitRebootsCount = value ? this.UnitRebootsCount : (uint?)null; }
    }
    private bool ShouldSerializeunit_reboots_count() { return UnitRebootsCountSpecified; }
    private void Resetunit_reboots_count() { UnitRebootsCountSpecified = false; }
    
    private uint? _LoginsCount;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"logins_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint LoginsCount
    {
      get { return _LoginsCount?? default(uint); }
      set { _LoginsCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool LoginsCountSpecified
    {
      get { return this._LoginsCount != null; }
      set { if (value == (this._LoginsCount== null)) this._LoginsCount = value ? this.LoginsCount : (uint?)null; }
    }
    private bool ShouldSerializelogins_count() { return LoginsCountSpecified; }
    private void Resetlogins_count() { LoginsCountSpecified = false; }
    
    private uint? _GsmRssi;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"gsm_rssi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint GsmRssi
    {
      get { return _GsmRssi?? default(uint); }
      set { _GsmRssi = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool GsmRssiSpecified
    {
      get { return this._GsmRssi != null; }
      set { if (value == (this._GsmRssi== null)) this._GsmRssi = value ? this.GsmRssi : (uint?)null; }
    }
    private bool ShouldSerializegsm_rssi() { return GsmRssiSpecified; }
    private void Resetgsm_rssi() { GsmRssiSpecified = false; }
    
    private float? _BatteryVoltage2;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"battery_voltage2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float BatteryVoltage2
    {
      get { return _BatteryVoltage2?? default(float); }
      set { _BatteryVoltage2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool BatteryVoltage2Specified
    {
      get { return this._BatteryVoltage2 != null; }
      set { if (value == (this._BatteryVoltage2== null)) this._BatteryVoltage2 = value ? this.BatteryVoltage2 : (float?)null; }
    }
    private bool ShouldSerializebattery_voltage2() { return BatteryVoltage2Specified; }
    private void Resetbattery_voltage2() { BatteryVoltage2Specified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}