//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: HistogramAcceleration0Proto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HistogramAcceleration0")]
  public partial class HistogramAcceleration0 : global::ProtoBuf.IExtensible
  {
    public HistogramAcceleration0()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.HistogramAcceleration0,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _TripDuration;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"trip_duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TripDuration
    {
      get { return _TripDuration?? default(uint); }
      set { _TripDuration = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripDurationSpecified
    {
      get { return this._TripDuration != null; }
      set { if (value == (this._TripDuration== null)) this._TripDuration = value ? this.TripDuration : (uint?)null; }
    }
    private bool ShouldSerializetrip_duration() { return TripDurationSpecified; }
    private void Resettrip_duration() { TripDurationSpecified = false; }
    
    private uint? _TripDistance;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"trip_distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TripDistance
    {
      get { return _TripDistance?? default(uint); }
      set { _TripDistance = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripDistanceSpecified
    {
      get { return this._TripDistance != null; }
      set { if (value == (this._TripDistance== null)) this._TripDistance = value ? this.TripDistance : (uint?)null; }
    }
    private bool ShouldSerializetrip_distance() { return TripDistanceSpecified; }
    private void Resettrip_distance() { TripDistanceSpecified = false; }
    
    private float? _YAxisData0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"y_axis_data0", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float YAxisData0
    {
      get { return _YAxisData0?? default(float); }
      set { _YAxisData0 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool YAxisData0Specified
    {
      get { return this._YAxisData0 != null; }
      set { if (value == (this._YAxisData0== null)) this._YAxisData0 = value ? this.YAxisData0 : (float?)null; }
    }
    private bool ShouldSerializey_axis_data0() { return YAxisData0Specified; }
    private void Resety_axis_data0() { YAxisData0Specified = false; }
    
    private float? _YAxisData1;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"y_axis_data1", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float YAxisData1
    {
      get { return _YAxisData1?? default(float); }
      set { _YAxisData1 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool YAxisData1Specified
    {
      get { return this._YAxisData1 != null; }
      set { if (value == (this._YAxisData1== null)) this._YAxisData1 = value ? this.YAxisData1 : (float?)null; }
    }
    private bool ShouldSerializey_axis_data1() { return YAxisData1Specified; }
    private void Resety_axis_data1() { YAxisData1Specified = false; }
    
    private float? _YAxisData2;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"y_axis_data2", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float YAxisData2
    {
      get { return _YAxisData2?? default(float); }
      set { _YAxisData2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool YAxisData2Specified
    {
      get { return this._YAxisData2 != null; }
      set { if (value == (this._YAxisData2== null)) this._YAxisData2 = value ? this.YAxisData2 : (float?)null; }
    }
    private bool ShouldSerializey_axis_data2() { return YAxisData2Specified; }
    private void Resety_axis_data2() { YAxisData2Specified = false; }
    
    private float? _YAxisData3;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"y_axis_data3", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float YAxisData3
    {
      get { return _YAxisData3?? default(float); }
      set { _YAxisData3 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool YAxisData3Specified
    {
      get { return this._YAxisData3 != null; }
      set { if (value == (this._YAxisData3== null)) this._YAxisData3 = value ? this.YAxisData3 : (float?)null; }
    }
    private bool ShouldSerializey_axis_data3() { return YAxisData3Specified; }
    private void Resety_axis_data3() { YAxisData3Specified = false; }
    
    private float? _YAxisData4;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"y_axis_data4", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float YAxisData4
    {
      get { return _YAxisData4?? default(float); }
      set { _YAxisData4 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool YAxisData4Specified
    {
      get { return this._YAxisData4 != null; }
      set { if (value == (this._YAxisData4== null)) this._YAxisData4 = value ? this.YAxisData4 : (float?)null; }
    }
    private bool ShouldSerializey_axis_data4() { return YAxisData4Specified; }
    private void Resety_axis_data4() { YAxisData4Specified = false; }
    
    private float? _YAxisData5;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"y_axis_data5", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float YAxisData5
    {
      get { return _YAxisData5?? default(float); }
      set { _YAxisData5 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool YAxisData5Specified
    {
      get { return this._YAxisData5 != null; }
      set { if (value == (this._YAxisData5== null)) this._YAxisData5 = value ? this.YAxisData5 : (float?)null; }
    }
    private bool ShouldSerializey_axis_data5() { return YAxisData5Specified; }
    private void Resety_axis_data5() { YAxisData5Specified = false; }
    
    private float? _YAxisData6;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"y_axis_data6", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float YAxisData6
    {
      get { return _YAxisData6?? default(float); }
      set { _YAxisData6 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool YAxisData6Specified
    {
      get { return this._YAxisData6 != null; }
      set { if (value == (this._YAxisData6== null)) this._YAxisData6 = value ? this.YAxisData6 : (float?)null; }
    }
    private bool ShouldSerializey_axis_data6() { return YAxisData6Specified; }
    private void Resety_axis_data6() { YAxisData6Specified = false; }
    
    private float? _YAxisData7;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"y_axis_data7", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float YAxisData7
    {
      get { return _YAxisData7?? default(float); }
      set { _YAxisData7 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool YAxisData7Specified
    {
      get { return this._YAxisData7 != null; }
      set { if (value == (this._YAxisData7== null)) this._YAxisData7 = value ? this.YAxisData7 : (float?)null; }
    }
    private bool ShouldSerializey_axis_data7() { return YAxisData7Specified; }
    private void Resety_axis_data7() { YAxisData7Specified = false; }
    
    private float? _YAxisData8;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"y_axis_data8", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float YAxisData8
    {
      get { return _YAxisData8?? default(float); }
      set { _YAxisData8 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool YAxisData8Specified
    {
      get { return this._YAxisData8 != null; }
      set { if (value == (this._YAxisData8== null)) this._YAxisData8 = value ? this.YAxisData8 : (float?)null; }
    }
    private bool ShouldSerializey_axis_data8() { return YAxisData8Specified; }
    private void Resety_axis_data8() { YAxisData8Specified = false; }
    
    private float? _YAxisData9;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"y_axis_data9", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float YAxisData9
    {
      get { return _YAxisData9?? default(float); }
      set { _YAxisData9 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool YAxisData9Specified
    {
      get { return this._YAxisData9 != null; }
      set { if (value == (this._YAxisData9== null)) this._YAxisData9 = value ? this.YAxisData9 : (float?)null; }
    }
    private bool ShouldSerializey_axis_data9() { return YAxisData9Specified; }
    private void Resety_axis_data9() { YAxisData9Specified = false; }
    
    private float? _XAxisData10;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"x_axis_data10", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float XAxisData10
    {
      get { return _XAxisData10?? default(float); }
      set { _XAxisData10 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool XAxisData10Specified
    {
      get { return this._XAxisData10 != null; }
      set { if (value == (this._XAxisData10== null)) this._XAxisData10 = value ? this.XAxisData10 : (float?)null; }
    }
    private bool ShouldSerializex_axis_data10() { return XAxisData10Specified; }
    private void Resetx_axis_data10() { XAxisData10Specified = false; }
    
    private float? _XAxisData11;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"x_axis_data11", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float XAxisData11
    {
      get { return _XAxisData11?? default(float); }
      set { _XAxisData11 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool XAxisData11Specified
    {
      get { return this._XAxisData11 != null; }
      set { if (value == (this._XAxisData11== null)) this._XAxisData11 = value ? this.XAxisData11 : (float?)null; }
    }
    private bool ShouldSerializex_axis_data11() { return XAxisData11Specified; }
    private void Resetx_axis_data11() { XAxisData11Specified = false; }
    
    private float? _XAxisData12;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"x_axis_data12", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float XAxisData12
    {
      get { return _XAxisData12?? default(float); }
      set { _XAxisData12 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool XAxisData12Specified
    {
      get { return this._XAxisData12 != null; }
      set { if (value == (this._XAxisData12== null)) this._XAxisData12 = value ? this.XAxisData12 : (float?)null; }
    }
    private bool ShouldSerializex_axis_data12() { return XAxisData12Specified; }
    private void Resetx_axis_data12() { XAxisData12Specified = false; }
    
    private float? _XAxisData13;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"x_axis_data13", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float XAxisData13
    {
      get { return _XAxisData13?? default(float); }
      set { _XAxisData13 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool XAxisData13Specified
    {
      get { return this._XAxisData13 != null; }
      set { if (value == (this._XAxisData13== null)) this._XAxisData13 = value ? this.XAxisData13 : (float?)null; }
    }
    private bool ShouldSerializex_axis_data13() { return XAxisData13Specified; }
    private void Resetx_axis_data13() { XAxisData13Specified = false; }
    
    private float? _XAxisData14;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"x_axis_data14", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float XAxisData14
    {
      get { return _XAxisData14?? default(float); }
      set { _XAxisData14 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool XAxisData14Specified
    {
      get { return this._XAxisData14 != null; }
      set { if (value == (this._XAxisData14== null)) this._XAxisData14 = value ? this.XAxisData14 : (float?)null; }
    }
    private bool ShouldSerializex_axis_data14() { return XAxisData14Specified; }
    private void Resetx_axis_data14() { XAxisData14Specified = false; }
    
    private float? _XAxisData15;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"x_axis_data15", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float XAxisData15
    {
      get { return _XAxisData15?? default(float); }
      set { _XAxisData15 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool XAxisData15Specified
    {
      get { return this._XAxisData15 != null; }
      set { if (value == (this._XAxisData15== null)) this._XAxisData15 = value ? this.XAxisData15 : (float?)null; }
    }
    private bool ShouldSerializex_axis_data15() { return XAxisData15Specified; }
    private void Resetx_axis_data15() { XAxisData15Specified = false; }
    
    private float? _XAxisData16;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"x_axis_data16", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float XAxisData16
    {
      get { return _XAxisData16?? default(float); }
      set { _XAxisData16 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool XAxisData16Specified
    {
      get { return this._XAxisData16 != null; }
      set { if (value == (this._XAxisData16== null)) this._XAxisData16 = value ? this.XAxisData16 : (float?)null; }
    }
    private bool ShouldSerializex_axis_data16() { return XAxisData16Specified; }
    private void Resetx_axis_data16() { XAxisData16Specified = false; }
    
    private float? _XAxisData17;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"x_axis_data17", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float XAxisData17
    {
      get { return _XAxisData17?? default(float); }
      set { _XAxisData17 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool XAxisData17Specified
    {
      get { return this._XAxisData17 != null; }
      set { if (value == (this._XAxisData17== null)) this._XAxisData17 = value ? this.XAxisData17 : (float?)null; }
    }
    private bool ShouldSerializex_axis_data17() { return XAxisData17Specified; }
    private void Resetx_axis_data17() { XAxisData17Specified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}