//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: ImAliveProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ImAlive")]
  public partial class ImAlive : global::ProtoBuf.IExtensible
  {
    public ImAlive()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.ImAlive,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _MajorVersion;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"major_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MajorVersion
    {
      get { return _MajorVersion?? default(uint); }
      set { _MajorVersion = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MajorVersionSpecified
    {
      get { return this._MajorVersion != null; }
      set { if (value == (this._MajorVersion== null)) this._MajorVersion = value ? this.MajorVersion : (uint?)null; }
    }
    private bool ShouldSerializemajor_version() { return MajorVersionSpecified; }
    private void Resetmajor_version() { MajorVersionSpecified = false; }
    
    private uint? _MinorVersion;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"minor_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MinorVersion
    {
      get { return _MinorVersion?? default(uint); }
      set { _MinorVersion = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MinorVersionSpecified
    {
      get { return this._MinorVersion != null; }
      set { if (value == (this._MinorVersion== null)) this._MinorVersion = value ? this.MinorVersion : (uint?)null; }
    }
    private bool ShouldSerializeminor_version() { return MinorVersionSpecified; }
    private void Resetminor_version() { MinorVersionSpecified = false; }
    
    private uint? _RunningHours;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"running_hours", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RunningHours
    {
      get { return _RunningHours?? default(uint); }
      set { _RunningHours = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool RunningHoursSpecified
    {
      get { return this._RunningHours != null; }
      set { if (value == (this._RunningHours== null)) this._RunningHours = value ? this.RunningHours : (uint?)null; }
    }
    private bool ShouldSerializerunning_hours() { return RunningHoursSpecified; }
    private void Resetrunning_hours() { RunningHoursSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}