//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: J1939ThresholdResetProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"J1939ThresholdReset")]
  public partial class J1939ThresholdReset : global::ProtoBuf.IExtensible
  {
    public J1939ThresholdReset()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.J1939ThresholdReset,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _ParameterGroupNumber;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"parameter_group_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ParameterGroupNumber
    {
      get { return _ParameterGroupNumber?? default(uint); }
      set { _ParameterGroupNumber = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ParameterGroupNumberSpecified
    {
      get { return this._ParameterGroupNumber != null; }
      set { if (value == (this._ParameterGroupNumber== null)) this._ParameterGroupNumber = value ? this.ParameterGroupNumber : (uint?)null; }
    }
    private bool ShouldSerializeparameter_group_number() { return ParameterGroupNumberSpecified; }
    private void Resetparameter_group_number() { ParameterGroupNumberSpecified = false; }
    
    private uint? _SuspectParameterNumber;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"suspect_parameter_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SuspectParameterNumber
    {
      get { return _SuspectParameterNumber?? default(uint); }
      set { _SuspectParameterNumber = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool SuspectParameterNumberSpecified
    {
      get { return this._SuspectParameterNumber != null; }
      set { if (value == (this._SuspectParameterNumber== null)) this._SuspectParameterNumber = value ? this.SuspectParameterNumber : (uint?)null; }
    }
    private bool ShouldSerializesuspect_parameter_number() { return SuspectParameterNumberSpecified; }
    private void Resetsuspect_parameter_number() { SuspectParameterNumberSpecified = false; }
    
    private uint? _CurrentMeasuredValue;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"current_measured_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CurrentMeasuredValue
    {
      get { return _CurrentMeasuredValue?? default(uint); }
      set { _CurrentMeasuredValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool CurrentMeasuredValueSpecified
    {
      get { return this._CurrentMeasuredValue != null; }
      set { if (value == (this._CurrentMeasuredValue== null)) this._CurrentMeasuredValue = value ? this.CurrentMeasuredValue : (uint?)null; }
    }
    private bool ShouldSerializecurrent_measured_value() { return CurrentMeasuredValueSpecified; }
    private void Resetcurrent_measured_value() { CurrentMeasuredValueSpecified = false; }
    
    private uint? _Threshold;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"threshold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Threshold
    {
      get { return _Threshold?? default(uint); }
      set { _Threshold = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ThresholdSpecified
    {
      get { return this._Threshold != null; }
      set { if (value == (this._Threshold== null)) this._Threshold = value ? this.Threshold : (uint?)null; }
    }
    private bool ShouldSerializethreshold() { return ThresholdSpecified; }
    private void Resetthreshold() { ThresholdSpecified = false; }
    
    private uint? _MinimumOrMaximum;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"minimum_or_maximum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MinimumOrMaximum
    {
      get { return _MinimumOrMaximum?? default(uint); }
      set { _MinimumOrMaximum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MinimumOrMaximumSpecified
    {
      get { return this._MinimumOrMaximum != null; }
      set { if (value == (this._MinimumOrMaximum== null)) this._MinimumOrMaximum = value ? this.MinimumOrMaximum : (uint?)null; }
    }
    private bool ShouldSerializeminimum_or_maximum() { return MinimumOrMaximumSpecified; }
    private void Resetminimum_or_maximum() { MinimumOrMaximumSpecified = false; }
    
    private uint? _TotalOdometer;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"total_odometer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TotalOdometer
    {
      get { return _TotalOdometer?? default(uint); }
      set { _TotalOdometer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TotalOdometerSpecified
    {
      get { return this._TotalOdometer != null; }
      set { if (value == (this._TotalOdometer== null)) this._TotalOdometer = value ? this.TotalOdometer : (uint?)null; }
    }
    private bool ShouldSerializetotal_odometer() { return TotalOdometerSpecified; }
    private void Resettotal_odometer() { TotalOdometerSpecified = false; }
    
    private uint? _TripOdometer;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"trip_odometer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TripOdometer
    {
      get { return _TripOdometer?? default(uint); }
      set { _TripOdometer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripOdometerSpecified
    {
      get { return this._TripOdometer != null; }
      set { if (value == (this._TripOdometer== null)) this._TripOdometer = value ? this.TripOdometer : (uint?)null; }
    }
    private bool ShouldSerializetrip_odometer() { return TripOdometerSpecified; }
    private void Resettrip_odometer() { TripOdometerSpecified = false; }
    
    private uint? _TripTime;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"trip_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TripTime
    {
      get { return _TripTime?? default(uint); }
      set { _TripTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripTimeSpecified
    {
      get { return this._TripTime != null; }
      set { if (value == (this._TripTime== null)) this._TripTime = value ? this.TripTime : (uint?)null; }
    }
    private bool ShouldSerializetrip_time() { return TripTimeSpecified; }
    private void Resettrip_time() { TripTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}