//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: J1939PeriodicParameterUpdateProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"J1939PeriodicParameterUpdate")]
  public partial class J1939PeriodicParameterUpdate : global::ProtoBuf.IExtensible
  {
    public J1939PeriodicParameterUpdate()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.J1939PeriodicParameterUpdate,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _ParameterGroupNumber;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"parameter_group_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ParameterGroupNumber
    {
      get { return _ParameterGroupNumber?? default(uint); }
      set { _ParameterGroupNumber = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ParameterGroupNumberSpecified
    {
      get { return this._ParameterGroupNumber != null; }
      set { if (value == (this._ParameterGroupNumber== null)) this._ParameterGroupNumber = value ? this.ParameterGroupNumber : (uint?)null; }
    }
    private bool ShouldSerializeparameter_group_number() { return ParameterGroupNumberSpecified; }
    private void Resetparameter_group_number() { ParameterGroupNumberSpecified = false; }
    
    private uint? _SuspectParameterNumber;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"suspect_parameter_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SuspectParameterNumber
    {
      get { return _SuspectParameterNumber?? default(uint); }
      set { _SuspectParameterNumber = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool SuspectParameterNumberSpecified
    {
      get { return this._SuspectParameterNumber != null; }
      set { if (value == (this._SuspectParameterNumber== null)) this._SuspectParameterNumber = value ? this.SuspectParameterNumber : (uint?)null; }
    }
    private bool ShouldSerializesuspect_parameter_number() { return SuspectParameterNumberSpecified; }
    private void Resetsuspect_parameter_number() { SuspectParameterNumberSpecified = false; }
    
    private uint? _CurrentMeasuredValue;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"current_measured_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CurrentMeasuredValue
    {
      get { return _CurrentMeasuredValue?? default(uint); }
      set { _CurrentMeasuredValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool CurrentMeasuredValueSpecified
    {
      get { return this._CurrentMeasuredValue != null; }
      set { if (value == (this._CurrentMeasuredValue== null)) this._CurrentMeasuredValue = value ? this.CurrentMeasuredValue : (uint?)null; }
    }
    private bool ShouldSerializecurrent_measured_value() { return CurrentMeasuredValueSpecified; }
    private void Resetcurrent_measured_value() { CurrentMeasuredValueSpecified = false; }
    
    private uint? _ParameterGroupNumber2;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"parameter_group_number2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ParameterGroupNumber2
    {
      get { return _ParameterGroupNumber2?? default(uint); }
      set { _ParameterGroupNumber2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ParameterGroupNumber2Specified
    {
      get { return this._ParameterGroupNumber2 != null; }
      set { if (value == (this._ParameterGroupNumber2== null)) this._ParameterGroupNumber2 = value ? this.ParameterGroupNumber2 : (uint?)null; }
    }
    private bool ShouldSerializeparameter_group_number2() { return ParameterGroupNumber2Specified; }
    private void Resetparameter_group_number2() { ParameterGroupNumber2Specified = false; }
    
    private uint? _SuspectParameterNumber2;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"suspect_parameter_number2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SuspectParameterNumber2
    {
      get { return _SuspectParameterNumber2?? default(uint); }
      set { _SuspectParameterNumber2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool SuspectParameterNumber2Specified
    {
      get { return this._SuspectParameterNumber2 != null; }
      set { if (value == (this._SuspectParameterNumber2== null)) this._SuspectParameterNumber2 = value ? this.SuspectParameterNumber2 : (uint?)null; }
    }
    private bool ShouldSerializesuspect_parameter_number2() { return SuspectParameterNumber2Specified; }
    private void Resetsuspect_parameter_number2() { SuspectParameterNumber2Specified = false; }
    
    private uint? _CurrentMeasuredValue2;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"current_measured_value2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CurrentMeasuredValue2
    {
      get { return _CurrentMeasuredValue2?? default(uint); }
      set { _CurrentMeasuredValue2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool CurrentMeasuredValue2Specified
    {
      get { return this._CurrentMeasuredValue2 != null; }
      set { if (value == (this._CurrentMeasuredValue2== null)) this._CurrentMeasuredValue2 = value ? this.CurrentMeasuredValue2 : (uint?)null; }
    }
    private bool ShouldSerializecurrent_measured_value2() { return CurrentMeasuredValue2Specified; }
    private void Resetcurrent_measured_value2() { CurrentMeasuredValue2Specified = false; }
    
    private uint? _TotalOdometer;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"total_odometer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TotalOdometer
    {
      get { return _TotalOdometer?? default(uint); }
      set { _TotalOdometer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TotalOdometerSpecified
    {
      get { return this._TotalOdometer != null; }
      set { if (value == (this._TotalOdometer== null)) this._TotalOdometer = value ? this.TotalOdometer : (uint?)null; }
    }
    private bool ShouldSerializetotal_odometer() { return TotalOdometerSpecified; }
    private void Resettotal_odometer() { TotalOdometerSpecified = false; }
    
    private uint? _TripOdometer;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"trip_odometer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TripOdometer
    {
      get { return _TripOdometer?? default(uint); }
      set { _TripOdometer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripOdometerSpecified
    {
      get { return this._TripOdometer != null; }
      set { if (value == (this._TripOdometer== null)) this._TripOdometer = value ? this.TripOdometer : (uint?)null; }
    }
    private bool ShouldSerializetrip_odometer() { return TripOdometerSpecified; }
    private void Resettrip_odometer() { TripOdometerSpecified = false; }
    
    private uint? _TripTime;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"trip_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TripTime
    {
      get { return _TripTime?? default(uint); }
      set { _TripTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripTimeSpecified
    {
      get { return this._TripTime != null; }
      set { if (value == (this._TripTime== null)) this._TripTime = value ? this.TripTime : (uint?)null; }
    }
    private bool ShouldSerializetrip_time() { return TripTimeSpecified; }
    private void Resettrip_time() { TripTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}