//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: MILStatusProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MILStatus")]
  public partial class MILStatus : global::ProtoBuf.IExtensible
  {
    public MILStatus()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.MILStatus,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _DtcCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"dtc_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint DtcCount
    {
      get { return _DtcCount?? default(uint); }
      set { _DtcCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DtcCountSpecified
    {
      get { return this._DtcCount != null; }
      set { if (value == (this._DtcCount== null)) this._DtcCount = value ? this.DtcCount : (uint?)null; }
    }
    private bool ShouldSerializedtc_count() { return DtcCountSpecified; }
    private void Resetdtc_count() { DtcCountSpecified = false; }
    
    private uint? _Dtc1;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dtc1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Dtc1
    {
      get { return _Dtc1?? default(uint); }
      set { _Dtc1 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Dtc1Specified
    {
      get { return this._Dtc1 != null; }
      set { if (value == (this._Dtc1== null)) this._Dtc1 = value ? this.Dtc1 : (uint?)null; }
    }
    private bool ShouldSerializedtc1() { return Dtc1Specified; }
    private void Resetdtc1() { Dtc1Specified = false; }
    
    private uint? _Dtc2;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dtc2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Dtc2
    {
      get { return _Dtc2?? default(uint); }
      set { _Dtc2 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Dtc2Specified
    {
      get { return this._Dtc2 != null; }
      set { if (value == (this._Dtc2== null)) this._Dtc2 = value ? this.Dtc2 : (uint?)null; }
    }
    private bool ShouldSerializedtc2() { return Dtc2Specified; }
    private void Resetdtc2() { Dtc2Specified = false; }
    
    private uint? _Dtc3;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"dtc3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Dtc3
    {
      get { return _Dtc3?? default(uint); }
      set { _Dtc3 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Dtc3Specified
    {
      get { return this._Dtc3 != null; }
      set { if (value == (this._Dtc3== null)) this._Dtc3 = value ? this.Dtc3 : (uint?)null; }
    }
    private bool ShouldSerializedtc3() { return Dtc3Specified; }
    private void Resetdtc3() { Dtc3Specified = false; }
    
    private uint? _Dtc4;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"dtc4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Dtc4
    {
      get { return _Dtc4?? default(uint); }
      set { _Dtc4 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Dtc4Specified
    {
      get { return this._Dtc4 != null; }
      set { if (value == (this._Dtc4== null)) this._Dtc4 = value ? this.Dtc4 : (uint?)null; }
    }
    private bool ShouldSerializedtc4() { return Dtc4Specified; }
    private void Resetdtc4() { Dtc4Specified = false; }
    
    private uint? _Dtc5;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"dtc5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Dtc5
    {
      get { return _Dtc5?? default(uint); }
      set { _Dtc5 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Dtc5Specified
    {
      get { return this._Dtc5 != null; }
      set { if (value == (this._Dtc5== null)) this._Dtc5 = value ? this.Dtc5 : (uint?)null; }
    }
    private bool ShouldSerializedtc5() { return Dtc5Specified; }
    private void Resetdtc5() { Dtc5Specified = false; }
    
    private uint? _Dtc6;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"dtc6", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Dtc6
    {
      get { return _Dtc6?? default(uint); }
      set { _Dtc6 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Dtc6Specified
    {
      get { return this._Dtc6 != null; }
      set { if (value == (this._Dtc6== null)) this._Dtc6 = value ? this.Dtc6 : (uint?)null; }
    }
    private bool ShouldSerializedtc6() { return Dtc6Specified; }
    private void Resetdtc6() { Dtc6Specified = false; }
    
    private uint? _Dtc7;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"dtc7", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Dtc7
    {
      get { return _Dtc7?? default(uint); }
      set { _Dtc7 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Dtc7Specified
    {
      get { return this._Dtc7 != null; }
      set { if (value == (this._Dtc7== null)) this._Dtc7 = value ? this.Dtc7 : (uint?)null; }
    }
    private bool ShouldSerializedtc7() { return Dtc7Specified; }
    private void Resetdtc7() { Dtc7Specified = false; }
    
    private uint? _Dtc8;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"dtc8", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Dtc8
    {
      get { return _Dtc8?? default(uint); }
      set { _Dtc8 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Dtc8Specified
    {
      get { return this._Dtc8 != null; }
      set { if (value == (this._Dtc8== null)) this._Dtc8 = value ? this.Dtc8 : (uint?)null; }
    }
    private bool ShouldSerializedtc8() { return Dtc8Specified; }
    private void Resetdtc8() { Dtc8Specified = false; }
    
    private uint? _Dtc9;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"dtc9", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Dtc9
    {
      get { return _Dtc9?? default(uint); }
      set { _Dtc9 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Dtc9Specified
    {
      get { return this._Dtc9 != null; }
      set { if (value == (this._Dtc9== null)) this._Dtc9 = value ? this.Dtc9 : (uint?)null; }
    }
    private bool ShouldSerializedtc9() { return Dtc9Specified; }
    private void Resetdtc9() { Dtc9Specified = false; }
    
    private uint? _Dtc10;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"dtc10", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Dtc10
    {
      get { return _Dtc10?? default(uint); }
      set { _Dtc10 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Dtc10Specified
    {
      get { return this._Dtc10 != null; }
      set { if (value == (this._Dtc10== null)) this._Dtc10 = value ? this.Dtc10 : (uint?)null; }
    }
    private bool ShouldSerializedtc10() { return Dtc10Specified; }
    private void Resetdtc10() { Dtc10Specified = false; }
    
    private uint? _Dtc11;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"dtc11", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Dtc11
    {
      get { return _Dtc11?? default(uint); }
      set { _Dtc11 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Dtc11Specified
    {
      get { return this._Dtc11 != null; }
      set { if (value == (this._Dtc11== null)) this._Dtc11 = value ? this.Dtc11 : (uint?)null; }
    }
    private bool ShouldSerializedtc11() { return Dtc11Specified; }
    private void Resetdtc11() { Dtc11Specified = false; }
    
    private uint? _Dtc12;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"dtc12", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Dtc12
    {
      get { return _Dtc12?? default(uint); }
      set { _Dtc12 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Dtc12Specified
    {
      get { return this._Dtc12 != null; }
      set { if (value == (this._Dtc12== null)) this._Dtc12 = value ? this.Dtc12 : (uint?)null; }
    }
    private bool ShouldSerializedtc12() { return Dtc12Specified; }
    private void Resetdtc12() { Dtc12Specified = false; }
    
    private uint? _Dtc13;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"dtc13", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Dtc13
    {
      get { return _Dtc13?? default(uint); }
      set { _Dtc13 = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Dtc13Specified
    {
      get { return this._Dtc13 != null; }
      set { if (value == (this._Dtc13== null)) this._Dtc13 = value ? this.Dtc13 : (uint?)null; }
    }
    private bool ShouldSerializedtc13() { return Dtc13Specified; }
    private void Resetdtc13() { Dtc13Specified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}