//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: NonTripPositionProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NonTripPosition")]
  public partial class NonTripPosition : global::ProtoBuf.IExtensible
  {
    public NonTripPosition()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.NonTripPosition,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _SmsCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"sms_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SmsCount
    {
      get { return _SmsCount?? default(uint); }
      set { _SmsCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool SmsCountSpecified
    {
      get { return this._SmsCount != null; }
      set { if (value == (this._SmsCount== null)) this._SmsCount = value ? this.SmsCount : (uint?)null; }
    }
    private bool ShouldSerializesms_count() { return SmsCountSpecified; }
    private void Resetsms_count() { SmsCountSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}