//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: RFIDInformationProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RFIDInformation")]
  public partial class RFIDInformation : global::ProtoBuf.IExtensible
  {
    public RFIDInformation()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.RFIDInformation,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private ulong? _RfidValue;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rfid_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong RfidValue
    {
      get { return _RfidValue?? default(ulong); }
      set { _RfidValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool RfidValueSpecified
    {
      get { return this._RfidValue != null; }
      set { if (value == (this._RfidValue== null)) this._RfidValue = value ? this.RfidValue : (ulong?)null; }
    }
    private bool ShouldSerializerfid_value() { return RfidValueSpecified; }
    private void Resetrfid_value() { RfidValueSpecified = false; }
    
    private ulong? _RfidExtendedValue;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rfid_extended_value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong RfidExtendedValue
    {
      get { return _RfidExtendedValue?? default(ulong); }
      set { _RfidExtendedValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool RfidExtendedValueSpecified
    {
      get { return this._RfidExtendedValue != null; }
      set { if (value == (this._RfidExtendedValue== null)) this._RfidExtendedValue = value ? this.RfidExtendedValue : (ulong?)null; }
    }
    private bool ShouldSerializerfid_extended_value() { return RfidExtendedValueSpecified; }
    private void Resetrfid_extended_value() { RfidExtendedValueSpecified = false; }
    
    private uint? _RfidType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rfid_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RfidType
    {
      get { return _RfidType?? default(uint); }
      set { _RfidType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool RfidTypeSpecified
    {
      get { return this._RfidType != null; }
      set { if (value == (this._RfidType== null)) this._RfidType = value ? this.RfidType : (uint?)null; }
    }
    private bool ShouldSerializerfid_type() { return RfidTypeSpecified; }
    private void Resetrfid_type() { RfidTypeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}