//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: SpeedingProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Speeding")]
  public partial class Speeding : global::ProtoBuf.IExtensible
  {
    public Speeding()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.Speeding,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _SpeedLimit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"speed_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SpeedLimit
    {
      get { return _SpeedLimit?? default(uint); }
      set { _SpeedLimit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool SpeedLimitSpecified
    {
      get { return this._SpeedLimit != null; }
      set { if (value == (this._SpeedLimit== null)) this._SpeedLimit = value ? this.SpeedLimit : (uint?)null; }
    }
    private bool ShouldSerializespeed_limit() { return SpeedLimitSpecified; }
    private void Resetspeed_limit() { SpeedLimitSpecified = false; }
    
    private uint? _MaximumSpeed;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maximum_speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MaximumSpeed
    {
      get { return _MaximumSpeed?? default(uint); }
      set { _MaximumSpeed = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool MaximumSpeedSpecified
    {
      get { return this._MaximumSpeed != null; }
      set { if (value == (this._MaximumSpeed== null)) this._MaximumSpeed = value ? this.MaximumSpeed : (uint?)null; }
    }
    private bool ShouldSerializemaximum_speed() { return MaximumSpeedSpecified; }
    private void Resetmaximum_speed() { MaximumSpeedSpecified = false; }
    
    private uint? _DurationSeconds;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"duration_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint DurationSeconds
    {
      get { return _DurationSeconds?? default(uint); }
      set { _DurationSeconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DurationSecondsSpecified
    {
      get { return this._DurationSeconds != null; }
      set { if (value == (this._DurationSeconds== null)) this._DurationSeconds = value ? this.DurationSeconds : (uint?)null; }
    }
    private bool ShouldSerializeduration_seconds() { return DurationSecondsSpecified; }
    private void Resetduration_seconds() { DurationSecondsSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}