//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: StartOfExcessiveRpmProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartOfExcessiveRpm")]
  public partial class StartOfExcessiveRpm : global::ProtoBuf.IExtensible
  {
    public StartOfExcessiveRpm()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.StartOfExcessiveRpm,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _RpmLimit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rpm_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint RpmLimit
    {
      get { return _RpmLimit?? default(uint); }
      set { _RpmLimit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool RpmLimitSpecified
    {
      get { return this._RpmLimit != null; }
      set { if (value == (this._RpmLimit== null)) this._RpmLimit = value ? this.RpmLimit : (uint?)null; }
    }
    private bool ShouldSerializerpm_limit() { return RpmLimitSpecified; }
    private void Resetrpm_limit() { RpmLimitSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}