//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: StartOfSpeedingProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StartOfSpeeding")]
  public partial class StartOfSpeeding : global::ProtoBuf.IExtensible
  {
    public StartOfSpeeding()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.StartOfSpeeding,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _SpeedLimit;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"speed_limit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint SpeedLimit
    {
      get { return _SpeedLimit?? default(uint); }
      set { _SpeedLimit = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool SpeedLimitSpecified
    {
      get { return this._SpeedLimit != null; }
      set { if (value == (this._SpeedLimit== null)) this._SpeedLimit = value ? this.SpeedLimit : (uint?)null; }
    }
    private bool ShouldSerializespeed_limit() { return SpeedLimitSpecified; }
    private void Resetspeed_limit() { SpeedLimitSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}