//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: Temperature1NormalProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Temperature1Normal")]
  public partial class Temperature1Normal : global::ProtoBuf.IExtensible
  {
    public Temperature1Normal()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.Temperature1Normal,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _DurationSeconds;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"duration_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint DurationSeconds
    {
      get { return _DurationSeconds?? default(uint); }
      set { _DurationSeconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool DurationSecondsSpecified
    {
      get { return this._DurationSeconds != null; }
      set { if (value == (this._DurationSeconds== null)) this._DurationSeconds = value ? this.DurationSeconds : (uint?)null; }
    }
    private bool ShouldSerializeduration_seconds() { return DurationSecondsSpecified; }
    private void Resetduration_seconds() { DurationSecondsSpecified = false; }
    
    private int? _ValueDegrees;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"value_degrees", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ValueDegrees
    {
      get { return _ValueDegrees?? default(int); }
      set { _ValueDegrees = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ValueDegreesSpecified
    {
      get { return this._ValueDegrees != null; }
      set { if (value == (this._ValueDegrees== null)) this._ValueDegrees = value ? this.ValueDegrees : (int?)null; }
    }
    private bool ShouldSerializevalue_degrees() { return ValueDegreesSpecified; }
    private void Resetvalue_degrees() { ValueDegreesSpecified = false; }
    
    private int? _HighThresholdDegrees;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"high_threshold_degrees", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int HighThresholdDegrees
    {
      get { return _HighThresholdDegrees?? default(int); }
      set { _HighThresholdDegrees = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool HighThresholdDegreesSpecified
    {
      get { return this._HighThresholdDegrees != null; }
      set { if (value == (this._HighThresholdDegrees== null)) this._HighThresholdDegrees = value ? this.HighThresholdDegrees : (int?)null; }
    }
    private bool ShouldSerializehigh_threshold_degrees() { return HighThresholdDegreesSpecified; }
    private void Resethigh_threshold_degrees() { HighThresholdDegreesSpecified = false; }
    
    private int? _LowThresholdDegrees;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"low_threshold_degrees", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int LowThresholdDegrees
    {
      get { return _LowThresholdDegrees?? default(int); }
      set { _LowThresholdDegrees = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool LowThresholdDegreesSpecified
    {
      get { return this._LowThresholdDegrees != null; }
      set { if (value == (this._LowThresholdDegrees== null)) this._LowThresholdDegrees = value ? this.LowThresholdDegrees : (int?)null; }
    }
    private bool ShouldSerializelow_threshold_degrees() { return LowThresholdDegreesSpecified; }
    private void Resetlow_threshold_degrees() { LowThresholdDegreesSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}