//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: TripStartupProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TripStartup")]
  public partial class TripStartup : global::ProtoBuf.IExtensible
  {
    public TripStartup()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.TripStartup,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _TripId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"trip_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TripId
    {
      get { return _TripId?? default(uint); }
      set { _TripId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripIdSpecified
    {
      get { return this._TripId != null; }
      set { if (value == (this._TripId== null)) this._TripId = value ? this.TripId : (uint?)null; }
    }
    private bool ShouldSerializetrip_id() { return TripIdSpecified; }
    private void Resettrip_id() { TripIdSpecified = false; }
    
    private uint? _TripStartDelaySeconds;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"trip_start_delay_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TripStartDelaySeconds
    {
      get { return _TripStartDelaySeconds?? default(uint); }
      set { _TripStartDelaySeconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripStartDelaySecondsSpecified
    {
      get { return this._TripStartDelaySeconds != null; }
      set { if (value == (this._TripStartDelaySeconds== null)) this._TripStartDelaySeconds = value ? this.TripStartDelaySeconds : (uint?)null; }
    }
    private bool ShouldSerializetrip_start_delay_seconds() { return TripStartDelaySecondsSpecified; }
    private void Resettrip_start_delay_seconds() { TripStartDelaySecondsSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}