//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: TripShutdownProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TripShutdown")]
  public partial class TripShutdown : global::ProtoBuf.IExtensible
  {
    public TripShutdown()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.TripShutdown,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _TripId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"trip_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TripId
    {
      get { return _TripId?? default(uint); }
      set { _TripId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripIdSpecified
    {
      get { return this._TripId != null; }
      set { if (value == (this._TripId== null)) this._TripId = value ? this.TripId : (uint?)null; }
    }
    private bool ShouldSerializetrip_id() { return TripIdSpecified; }
    private void Resettrip_id() { TripIdSpecified = false; }
    
    private uint? _TripStartDelaySeconds;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"trip_start_delay_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TripStartDelaySeconds
    {
      get { return _TripStartDelaySeconds?? default(uint); }
      set { _TripStartDelaySeconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripStartDelaySecondsSpecified
    {
      get { return this._TripStartDelaySeconds != null; }
      set { if (value == (this._TripStartDelaySeconds== null)) this._TripStartDelaySeconds = value ? this.TripStartDelaySeconds : (uint?)null; }
    }
    private bool ShouldSerializetrip_start_delay_seconds() { return TripStartDelaySecondsSpecified; }
    private void Resettrip_start_delay_seconds() { TripStartDelaySecondsSpecified = false; }
    
    private uint? _GreenTimePercent;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"green_time_percent", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint GreenTimePercent
    {
      get { return _GreenTimePercent?? default(uint); }
      set { _GreenTimePercent = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool GreenTimePercentSpecified
    {
      get { return this._GreenTimePercent != null; }
      set { if (value == (this._GreenTimePercent== null)) this._GreenTimePercent = value ? this.GreenTimePercent : (uint?)null; }
    }
    private bool ShouldSerializegreen_time_percent() { return GreenTimePercentSpecified; }
    private void Resetgreen_time_percent() { GreenTimePercentSpecified = false; }
    
    private uint? _TripDurationSeconds;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"trip_duration_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TripDurationSeconds
    {
      get { return _TripDurationSeconds?? default(uint); }
      set { _TripDurationSeconds = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripDurationSecondsSpecified
    {
      get { return this._TripDurationSeconds != null; }
      set { if (value == (this._TripDurationSeconds== null)) this._TripDurationSeconds = value ? this.TripDurationSeconds : (uint?)null; }
    }
    private bool ShouldSerializetrip_duration_seconds() { return TripDurationSecondsSpecified; }
    private void Resettrip_duration_seconds() { TripDurationSecondsSpecified = false; }
    
    private uint? _TripDistanceMeters;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"trip_distance_meters", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint TripDistanceMeters
    {
      get { return _TripDistanceMeters?? default(uint); }
      set { _TripDistanceMeters = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool TripDistanceMetersSpecified
    {
      get { return this._TripDistanceMeters != null; }
      set { if (value == (this._TripDistanceMeters== null)) this._TripDistanceMeters = value ? this.TripDistanceMeters : (uint?)null; }
    }
    private bool ShouldSerializetrip_distance_meters() { return TripDistanceMetersSpecified; }
    private void Resettrip_distance_meters() { TripDistanceMetersSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}