//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: VehicleSignatureProto.proto
// Note: requires additional types generated from: EventHeaderProto.proto
// Note: requires additional types generated from: Enums/OBD2ProtocolProto.proto
using Scope.FiveC.Protocol.Events.Enums;

namespace Scope.FiveC.Protocol.Events
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VehicleSignature")]
  public partial class VehicleSignature : global::ProtoBuf.IExtensible
  {
    public VehicleSignature()
	{
		_Header = new EventHeader
		{
			TemplateId = (uint) ProtocolBufferTemplate.VehicleSignature,
		};
	}
    
    private EventHeader _Header;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"header", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public override EventHeader Header
    {
      get { return _Header; }
      set { _Header = value; }
    }
    private uint? _Reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Reason
    {
      get { return _Reason?? default(uint); }
      set { _Reason = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ReasonSpecified
    {
      get { return this._Reason != null; }
      set { if (value == (this._Reason== null)) this._Reason = value ? this.Reason : (uint?)null; }
    }
    private bool ShouldSerializereason() { return ReasonSpecified; }
    private void Resetreason() { ReasonSpecified = false; }
    
    private OBD2Protocol? _Obd2Protocol;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"obd2_protocol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public OBD2Protocol Obd2Protocol
    {
      get { return _Obd2Protocol?? OBD2Protocol.OBD2_PROTOCOL_NOT_SUPPORTED; }
      set { _Obd2Protocol = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool Obd2ProtocolSpecified
    {
      get { return this._Obd2Protocol != null; }
      set { if (value == (this._Obd2Protocol== null)) this._Obd2Protocol = value ? this.Obd2Protocol : (OBD2Protocol?)null; }
    }
    private bool ShouldSerializeobd2_protocol() { return Obd2ProtocolSpecified; }
    private void Resetobd2_protocol() { Obd2ProtocolSpecified = false; }
    
    private string _Gpid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gpid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Gpid
    {
      get { return _Gpid?? ""; }
      set { _Gpid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool GpidSpecified
    {
      get { return this._Gpid != null; }
      set { if (value == (this._Gpid== null)) this._Gpid = value ? this.Gpid : (string)null; }
    }
    private bool ShouldSerializegpid() { return GpidSpecified; }
    private void Resetgpid() { GpidSpecified = false; }
    
    private uint? _AccelerometerAlpha;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"accelerometer_alpha", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AccelerometerAlpha
    {
      get { return _AccelerometerAlpha?? default(uint); }
      set { _AccelerometerAlpha = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool AccelerometerAlphaSpecified
    {
      get { return this._AccelerometerAlpha != null; }
      set { if (value == (this._AccelerometerAlpha== null)) this._AccelerometerAlpha = value ? this.AccelerometerAlpha : (uint?)null; }
    }
    private bool ShouldSerializeaccelerometer_alpha() { return AccelerometerAlphaSpecified; }
    private void Resetaccelerometer_alpha() { AccelerometerAlphaSpecified = false; }
    
    private uint? _AccelerometerBeta;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"accelerometer_beta", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AccelerometerBeta
    {
      get { return _AccelerometerBeta?? default(uint); }
      set { _AccelerometerBeta = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool AccelerometerBetaSpecified
    {
      get { return this._AccelerometerBeta != null; }
      set { if (value == (this._AccelerometerBeta== null)) this._AccelerometerBeta = value ? this.AccelerometerBeta : (uint?)null; }
    }
    private bool ShouldSerializeaccelerometer_beta() { return AccelerometerBetaSpecified; }
    private void Resetaccelerometer_beta() { AccelerometerBetaSpecified = false; }
    
    private uint? _AccelerometerGamma;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"accelerometer_gamma", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint AccelerometerGamma
    {
      get { return _AccelerometerGamma?? default(uint); }
      set { _AccelerometerGamma = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool AccelerometerGammaSpecified
    {
      get { return this._AccelerometerGamma != null; }
      set { if (value == (this._AccelerometerGamma== null)) this._AccelerometerGamma = value ? this.AccelerometerGamma : (uint?)null; }
    }
    private bool ShouldSerializeaccelerometer_gamma() { return AccelerometerGammaSpecified; }
    private void Resetaccelerometer_gamma() { AccelerometerGammaSpecified = false; }
    
    private string _GearRatioSignature;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"gear_ratio_signature", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string GearRatioSignature
    {
      get { return _GearRatioSignature?? ""; }
      set { _GearRatioSignature = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool GearRatioSignatureSpecified
    {
      get { return this._GearRatioSignature != null; }
      set { if (value == (this._GearRatioSignature== null)) this._GearRatioSignature = value ? this.GearRatioSignature : (string)null; }
    }
    private bool ShouldSerializegear_ratio_signature() { return GearRatioSignatureSpecified; }
    private void Resetgear_ratio_signature() { GearRatioSignatureSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}