//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: AccidentAnalysisClassificationAssistanceTypeProto.proto
namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"AccidentAnalysisClassificationAssistanceType")]
    public enum AccidentAnalysisClassificationAssistanceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_NOTHING", Value=0)]
      ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_NOTHING = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_CALL", Value=1)]
      ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_CALL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_AMBULANCE", Value=2)]
      ACCIDENT_ANALYSIS_CLASSIFICATION_ASSISTANCE_AMBULANCE = 2
    }
  
}