//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: BluetoothLowEnergyIOReasonTypeProto.proto
namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"BluetoothLowEnergyIOReasonType")]
    public enum BluetoothLowEnergyIOReasonType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLUETOOTH_LOW_ENERGY_IO_REASON_UNDEFINED", Value=0)]
      BLUETOOTH_LOW_ENERGY_IO_REASON_UNDEFINED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLUETOOTH_LOW_ENERGY_IO_REASON_INPUT_CHANGED", Value=3)]
      BLUETOOTH_LOW_ENERGY_IO_REASON_INPUT_CHANGED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLUETOOTH_LOW_ENERGY_IO_REASON_OUTPUT_CHANGED", Value=4)]
      BLUETOOTH_LOW_ENERGY_IO_REASON_OUTPUT_CHANGED = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLUETOOTH_LOW_ENERGY_IO_REASON_ACCELEROMETER_CHANGED", Value=5)]
      BLUETOOTH_LOW_ENERGY_IO_REASON_ACCELEROMETER_CHANGED = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLUETOOTH_LOW_ENERGY_IO_REASON_MOVEMENT_DETECTED", Value=6)]
      BLUETOOTH_LOW_ENERGY_IO_REASON_MOVEMENT_DETECTED = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLUETOOTH_LOW_ENERGY_IO_REASON_EXCESSIVE_SHOCK_DETECTED", Value=7)]
      BLUETOOTH_LOW_ENERGY_IO_REASON_EXCESSIVE_SHOCK_DETECTED = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLUETOOTH_LOW_ENERGY_IO_REASON_FALL_DETECTED", Value=8)]
      BLUETOOTH_LOW_ENERGY_IO_REASON_FALL_DETECTED = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BLUETOOTH_LOW_ENERGY_IO_REASON_DOUBLE_TAP_DETECTED", Value=9)]
      BLUETOOTH_LOW_ENERGY_IO_REASON_DOUBLE_TAP_DETECTED = 9
    }
  
}