//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: ConsumptionFuelTypeProto.proto
namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"ConsumptionFuelType")]
    public enum ConsumptionFuelType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONSUMPTION_FUEL_TYPE_PETROL", Value=0)]
      CONSUMPTION_FUEL_TYPE_PETROL = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONSUMPTION_FUEL_TYPE_DIESEL", Value=1)]
      CONSUMPTION_FUEL_TYPE_DIESEL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CONSUMPTION_FUEL_TYPE_LPGAS", Value=2)]
      CONSUMPTION_FUEL_TYPE_LPGAS = 2
    }
  
}