//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: DriverFatigueReasonTypeProto.proto
namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"DriverFatigueReasonType")]
    public enum DriverFatigueReasonType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DRIVER_FATIGUE_REASON_SPEED_UNSPECIFIED", Value=0)]
      DRIVER_FATIGUE_REASON_SPEED_UNSPECIFIED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DRIVER_FATIGUE_REASON_SPEED_MONITORING", Value=1)]
      DRIVER_FATIGUE_REASON_SPEED_MONITORING = 1
    }
  
}