//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: DriverFatigueSourceTypeProto.proto
namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"DriverFatigueSourceType")]
    public enum DriverFatigueSourceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DRIVER_FATIGUE_SOURCE_SPEED_MONITORING", Value=0)]
      DRIVER_FATIGUE_SOURCE_SPEED_MONITORING = 0
    }
  
}