//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: ForceDirectionTypeProto.proto
namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"ForceDirectionType")]
    public enum ForceDirectionType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_DIRECTION_NO_ACCIDENT", Value=0)]
      FORCE_DIRECTION_NO_ACCIDENT = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_DIRECTION_FRONT", Value=1)]
      FORCE_DIRECTION_FRONT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_DIRECTION_FRONT_LEFT", Value=2)]
      FORCE_DIRECTION_FRONT_LEFT = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_DIRECTION_LEFT", Value=3)]
      FORCE_DIRECTION_LEFT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_DIRECTION_REAR_LEFT", Value=4)]
      FORCE_DIRECTION_REAR_LEFT = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_DIRECTION_REAR", Value=5)]
      FORCE_DIRECTION_REAR = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_DIRECTION_REAR_RIGHT", Value=6)]
      FORCE_DIRECTION_REAR_RIGHT = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_DIRECTION_RIGHT", Value=7)]
      FORCE_DIRECTION_RIGHT = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_DIRECTION_FRONT_RIGHT", Value=8)]
      FORCE_DIRECTION_FRONT_RIGHT = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_DIRECTION_UPSIDE_DOWN", Value=9)]
      FORCE_DIRECTION_UPSIDE_DOWN = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_DIRECTION_LANE_CHANGE", Value=16)]
      FORCE_DIRECTION_LANE_CHANGE = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_DIRECTION_SWERVE", Value=17)]
      FORCE_DIRECTION_SWERVE = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FORCE_DIRECTION_SPEED_BUMP", Value=18)]
      FORCE_DIRECTION_SPEED_BUMP = 18
    }
  
}