//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: FuelConsumptionUnitOfMeasureTypeProto.proto
namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"FuelConsumptionUnitOfMeasureType")]
    public enum FuelConsumptionUnitOfMeasureType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_LITERS_PER_100_KM", Value=0)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_LITERS_PER_100_KM = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_KM_PER_LITER", Value=1)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_KM_PER_LITER = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_LITERS_PER_HOUR", Value=2)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_LITERS_PER_HOUR = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_KG_PER_100_KM", Value=3)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_KG_PER_100_KM = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_KG_PER_HOUR", Value=4)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_KG_PER_HOUR = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_KILOWATTS_PER_HOUR", Value=5)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_KILOWATTS_PER_HOUR = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE6", Value=6)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE6 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE7", Value=7)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE7 = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE8", Value=8)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE8 = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE9", Value=9)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE9 = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE10", Value=10)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE10 = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE11", Value=11)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE11 = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE12", Value=12)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE12 = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE13", Value=13)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE13 = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE14", Value=14)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE14 = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE15", Value=15)]
      FUEL_CONSUMPTION_UNIT_OF_MEASURE_RFE15 = 15
    }
  
}