//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: FuelConsumptionSourceTypeProto.proto
namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"FuelConsumptionSourceType")]
    public enum FuelConsumptionSourceType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_NOT_CONFIGURED", Value=0)]
      FUEL_CONSUMPTION_SOURCE_TYPE_NOT_CONFIGURED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_CAN_BUS", Value=1)]
      FUEL_CONSUMPTION_SOURCE_TYPE_CAN_BUS = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_OBD2", Value=2)]
      FUEL_CONSUMPTION_SOURCE_TYPE_OBD2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_J1708", Value=3)]
      FUEL_CONSUMPTION_SOURCE_TYPE_J1708 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_FLOWMETER", Value=4)]
      FUEL_CONSUMPTION_SOURCE_TYPE_FLOWMETER = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_CO2_MODEL", Value=5)]
      FUEL_CONSUMPTION_SOURCE_TYPE_CO2_MODEL = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_MASS_AIRFLOW", Value=6)]
      FUEL_CONSUMPTION_SOURCE_TYPE_MASS_AIRFLOW = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_FUEL_PROBE", Value=7)]
      FUEL_CONSUMPTION_SOURCE_TYPE_FUEL_PROBE = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_RFE8", Value=8)]
      FUEL_CONSUMPTION_SOURCE_TYPE_RFE8 = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_RFE9", Value=9)]
      FUEL_CONSUMPTION_SOURCE_TYPE_RFE9 = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_RFE10", Value=10)]
      FUEL_CONSUMPTION_SOURCE_TYPE_RFE10 = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_RFE11", Value=11)]
      FUEL_CONSUMPTION_SOURCE_TYPE_RFE11 = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_RFE12", Value=12)]
      FUEL_CONSUMPTION_SOURCE_TYPE_RFE12 = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_RFE13", Value=13)]
      FUEL_CONSUMPTION_SOURCE_TYPE_RFE13 = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_RFE14", Value=14)]
      FUEL_CONSUMPTION_SOURCE_TYPE_RFE14 = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"FUEL_CONSUMPTION_SOURCE_TYPE_RFE15", Value=15)]
      FUEL_CONSUMPTION_SOURCE_TYPE_RFE15 = 15
    }
  
}