//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: GeneralStatusTypeProto.proto
using System;

namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"GeneralStatusType")]
    [Flags]
	public enum GeneralStatusType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GENERAL_STATUS_IGNITION", Value=1)]
      GENERAL_STATUS_IGNITION = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GENERAL_STATUS_BATTERY", Value=2)]
      GENERAL_STATUS_BATTERY = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GENERAL_STATUS_GPS_INFORMATION_AVAILABLE", Value=4)]
      GENERAL_STATUS_GPS_INFORMATION_AVAILABLE = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GENERAL_STATUS_INPUT_OUTPUT_INFORMATION_AVAILABLE", Value=8)]
      GENERAL_STATUS_INPUT_OUTPUT_INFORMATION_AVAILABLE = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GENERAL_STATUS_GPS_POSITION_INVALID", Value=16)]
      GENERAL_STATUS_GPS_POSITION_INVALID = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GENERAL_STATUS_GPS_STATUS_VALID", Value=32)]
      GENERAL_STATUS_GPS_STATUS_VALID = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GENERAL_STATUS_GPS_ANTENNA_CONNECTED", Value=64)]
      GENERAL_STATUS_GPS_ANTENNA_CONNECTED = 64
    }
  
}