//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: GsmNoticeGsmJammingStatusTypeProto.proto
namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"GsmNoticeGsmJammingStatusType")]
    public enum GsmNoticeGsmJammingStatusType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GSM_NOTICE_JAMMING_STATUS_UNDEFINED", Value=0)]
      GSM_NOTICE_JAMMING_STATUS_UNDEFINED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GSM_NOTICE_JAMMING_STATUS_JAMMING_ACTIVE", Value=1)]
      GSM_NOTICE_JAMMING_STATUS_JAMMING_ACTIVE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GSM_NOTICE_JAMMING_STATUS_DEBOUNCE_JAMMING_ACTIVE", Value=2)]
      GSM_NOTICE_JAMMING_STATUS_DEBOUNCE_JAMMING_ACTIVE = 2
    }
  
}