//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: HealthMetricsFlagsProto.proto
using System;

namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"HealthMetricsFlags")]
    [Flags]
	public enum HealthMetricsFlags
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEALTH_METRICS_CONFIG_CHANGED", Value=1)]
      HEALTH_METRICS_CONFIG_CHANGED = 1
    }
  
}