//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: InputStatusTypeProto.proto
using System;

namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"InputStatusType")]
    [Flags]
	public enum InputStatusType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT1", Value=1)]
      INPUT_STATUS_INPUT1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT2", Value=2)]
      INPUT_STATUS_INPUT2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT3", Value=4)]
      INPUT_STATUS_INPUT3 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT4", Value=8)]
      INPUT_STATUS_INPUT4 = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT5", Value=16)]
      INPUT_STATUS_INPUT5 = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT6", Value=32)]
      INPUT_STATUS_INPUT6 = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT7", Value=64)]
      INPUT_STATUS_INPUT7 = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT8", Value=128)]
      INPUT_STATUS_INPUT8 = 128,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT9", Value=256)]
      INPUT_STATUS_INPUT9 = 256,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT10", Value=512)]
      INPUT_STATUS_INPUT10 = 512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT11", Value=1024)]
      INPUT_STATUS_INPUT11 = 1024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT12", Value=2048)]
      INPUT_STATUS_INPUT12 = 2048,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT13", Value=4096)]
      INPUT_STATUS_INPUT13 = 4096,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT14", Value=8192)]
      INPUT_STATUS_INPUT14 = 8192,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT15", Value=16384)]
      INPUT_STATUS_INPUT15 = 16384,
            
      [global::ProtoBuf.ProtoEnum(Name=@"INPUT_STATUS_INPUT16", Value=32768)]
      INPUT_STATUS_INPUT16 = 32768
    }
  
}