//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: LoadSensorReasonTypeProto.proto
namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"LoadSensorReasonType")]
    public enum LoadSensorReasonType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOAD_SENSOR_REASON_UNSPECIFIED", Value=0)]
      LOAD_SENSOR_REASON_UNSPECIFIED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOAD_SENSOR_REASON_PERIODIC", Value=3)]
      LOAD_SENSOR_REASON_PERIODIC = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOAD_SENSOR_REASON_TRIP_END", Value=4)]
      LOAD_SENSOR_REASON_TRIP_END = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOAD_SENSOR_REASON_TRIP_START", Value=5)]
      LOAD_SENSOR_REASON_TRIP_START = 5
    }
  
}