//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: OBD2ProtocolProto.proto
namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"OBD2Protocol")]
    public enum OBD2Protocol
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBD2_PROTOCOL_NOT_SUPPORTED", Value=0)]
      OBD2_PROTOCOL_NOT_SUPPORTED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBD2_PROTOCOL_ISO9141", Value=1)]
      OBD2_PROTOCOL_ISO9141 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBD2_PROTOCOL_KWP2000SLOW", Value=2)]
      OBD2_PROTOCOL_KWP2000SLOW = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBD2_PROTOCOL_KWP2000FAST", Value=3)]
      OBD2_PROTOCOL_KWP2000FAST = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBD2_PROTOCOL_CAN", Value=4)]
      OBD2_PROTOCOL_CAN = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBD2_PROTOCOL_J1850VPW", Value=5)]
      OBD2_PROTOCOL_J1850VPW = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBD2_PROTOCOL_VAG", Value=6)]
      OBD2_PROTOCOL_VAG = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBD2_PROTOCOL_KWP2000VAG", Value=7)]
      OBD2_PROTOCOL_KWP2000VAG = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OBD2_PROTOCOL_VAGTP20", Value=8)]
      OBD2_PROTOCOL_VAGTP20 = 8
    }
  
}