//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: OutputStatusTypeProto.proto
using System;

namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"OutputStatusType")]
    [Flags]
	public enum OutputStatusType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OUTPUT_STATUS_OUTPUT1", Value=1)]
      OUTPUT_STATUS_OUTPUT1 = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OUTPUT_STATUS_OUTPUT2", Value=2)]
      OUTPUT_STATUS_OUTPUT2 = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OUTPUT_STATUS_OUTPUT3", Value=4)]
      OUTPUT_STATUS_OUTPUT3 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OUTPUT_STATUS_OUTPUT4", Value=8)]
      OUTPUT_STATUS_OUTPUT4 = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OUTPUT_STATUS_OUTPUT5", Value=16)]
      OUTPUT_STATUS_OUTPUT5 = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OUTPUT_STATUS_OUTPUT6", Value=32)]
      OUTPUT_STATUS_OUTPUT6 = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OUTPUT_STATUS_OUTPUT7", Value=64)]
      OUTPUT_STATUS_OUTPUT7 = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OUTPUT_STATUS_OUTPUT8", Value=128)]
      OUTPUT_STATUS_OUTPUT8 = 128
    }
  
}