//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: TripSpeedSourceProto.proto
namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"TripSpeedSource")]
    public enum TripSpeedSource
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRIP_SPEED_SOURCE_NOT_SUPPORTED", Value=0)]
      TRIP_SPEED_SOURCE_NOT_SUPPORTED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRIP_SPEED_SOURCE_SPEED_SENSOR", Value=1)]
      TRIP_SPEED_SOURCE_SPEED_SENSOR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRIP_SPEED_SOURCE_GPS", Value=2)]
      TRIP_SPEED_SOURCE_GPS = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TRIP_SPEED_SOURCE_CANBUS", Value=4)]
      TRIP_SPEED_SOURCE_CANBUS = 4
    }
  
}