//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: VehicleSignatureReasonProto.proto
using System;

namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"VehicleSignatureReason")]
    [Flags]
	public enum VehicleSignatureReason
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"VEHICLE_SIGNATURE_REASON_GPID_CHANGED", Value=0)]
      VEHICLE_SIGNATURE_REASON_GPID_CHANGED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VEHICLE_SIGNATURE_REASON_ACC_CHANGED", Value=1)]
      VEHICLE_SIGNATURE_REASON_ACC_CHANGED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VEHICLE_SIGNATURE_REASON_GEAR_RATIOS_CHANGED", Value=2)]
      VEHICLE_SIGNATURE_REASON_GEAR_RATIOS_CHANGED = 2
    }
  
}