//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: VehicleVINReasonProto.proto
namespace Scope.FiveC.Protocol.Events.Enums
{
    [global::ProtoBuf.ProtoContract(Name=@"VehicleVINReason")]
    public enum VehicleVINReason
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"VEHICLE_REASON_VIN_CHANGED", Value=0)]
      VEHICLE_REASON_VIN_CHANGED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VEHICLE_REASON_VIN_NOT_AVAILABLE", Value=1)]
      VEHICLE_REASON_VIN_NOT_AVAILABLE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VEHICLE_REASON_OBD2_NOT_AVAILABLE", Value=2)]
      VEHICLE_REASON_OBD2_NOT_AVAILABLE = 2
    }
  
}